import { create } from 'zustand'

type Language = 'en' | 'bn'

interface LanguageState {
  lang: Language
  setLang: (lang: Language) => void
  toggle: () => void
  t: (key: string) => string
}

const translations: Record<string, Record<Language, string>> = {
  // ─── Navbar ───
  'nav.signIn': { en: 'Sign In', bn: 'সাইন ইন' },
  'nav.getStarted': { en: 'Get Started', bn: 'শুরু করুন' },
  'nav.documents': { en: 'Documents', bn: 'ডকুমেন্টস' },
  'nav.lightMode': { en: 'Light mode', bn: 'লাইট মোড' },
  'common.closeDialog': { en: 'Close dialog', bn: 'ডায়ালগ বন্ধ করুন' },
  'common.dialog': { en: 'Dialog', bn: 'ডায়ালগ' },
  'common.closeConfirmation': { en: 'Close confirmation', bn: 'নিশ্চিতকরণ বন্ধ করুন' },
  'common.confirmation': { en: 'Confirmation', bn: 'নিশ্চিতকরণ' },
  'common.confirmActionFailed': {
    en: 'The action could not be completed. Check your connection and try again.',
    bn: 'কাজটি সম্পন্ন করা যায়নি। সংযোগ পরীক্ষা করে আবার চেষ্টা করুন।',
  },
  'common.skipToContent': { en: 'Skip to main content', bn: 'মূল কনটেন্টে যান' },
  'common.loadingPage': { en: 'Loading page...', bn: 'পৃষ্ঠা লোড হচ্ছে...' },
  'common.loadingDocument': { en: 'Loading document...', bn: 'ডকুমেন্ট লোড হচ্ছে...' },
  'common.homeLabel': { en: 'Somadhan Sign home', bn: 'Somadhan Sign হোম' },
  'common.switchToBangla': { en: 'বাংলা, switch to Bangla', bn: 'বাংলা, বাংলায় পরিবর্তন করুন' },
  'common.switchToEnglish': { en: 'EN, switch to English', bn: 'EN, ইংরেজিতে পরিবর্তন করুন' },
  'common.openMenu': { en: 'Open menu', bn: 'মেনু খুলুন' },
  'common.closeMenu': { en: 'Close menu', bn: 'মেনু বন্ধ করুন' },
  'common.primaryNavigation': { en: 'Primary navigation', bn: 'প্রধান নেভিগেশন' },
  'common.mobileNavigation': { en: 'Mobile navigation', bn: 'মোবাইল নেভিগেশন' },
  'errorBoundary.title': { en: 'Something went wrong', bn: 'কিছু সমস্যা হয়েছে' },
  'errorBoundary.description': { en: 'Your work may still be saved. Reload the page to reconnect and continue.', bn: 'আপনার কাজ সংরক্ষিত থাকতে পারে। আবার সংযোগ করে চালিয়ে যেতে পৃষ্ঠাটি রিলোড করুন।' },
  'errorBoundary.reload': { en: 'Reload page', bn: 'পৃষ্ঠা রিলোড করুন' },
  'notFound.title': { en: 'This page could not be found', bn: 'এই পৃষ্ঠাটি পাওয়া যায়নি' },
  'notFound.description': { en: 'The link may be incorrect or the page may have moved.', bn: 'লিঙ্কটি ভুল হতে পারে অথবা পৃষ্ঠাটি সরানো হয়েছে।' },
  'notFound.returnHome': { en: 'Return home', bn: 'হোমে ফিরুন' },
  'nav.darkMode': { en: 'Dark mode', bn: 'ডার্ক মোড' },
  'nav.signOut': { en: 'Sign out', bn: 'সাইন আউট' },
  'nav.signingOut': { en: 'Signing out...', bn: 'সাইন আউট হচ্ছে...' },
  'nav.signOutFailed': { en: 'Could not sign out. Check your connection and try again.', bn: 'সাইন আউট করা যায়নি। সংযোগ পরীক্ষা করে আবার চেষ্টা করুন।' },

  // ─── Landing Page ───
  'landing.heroTitle1': { en: 'Sign documents with', bn: 'ডকুমেন্ট  সাইন  করুন' },
  'landing.heroTitle2': { 
    en: 'SomadhanSign', 
    bn: 'সমাধান  সাইন  দিয়ে'
  },
  'landing.heroDesc': {
    en: 'Upload documents, define signature fields, invite multiple signers, and get everything signed in one beautiful platform.',
    bn: 'ডকুমেন্ট আপলোড করুন, স্বাক্ষর ক্ষেত্র নির্ধারণ করুন, একাধিক স্বাক্ষরকারী আমন্ত্রণ করুন এবং একটি সুন্দর প্ল্যাটফর্মে সবকিছু স্বাক্ষরিত করুন।',
  },
  'landing.navProduct': { en: 'Product', bn: 'প্রোডাক্ট' },
  'landing.navCapabilities': { en: 'Capabilities', bn: 'সুবিধাসমূহ' },
  'landing.navSecurity': { en: 'Security', bn: 'নিরাপত্তা' },
  'landing.heroKicker': { en: 'Documents, ready for action', bn: 'ডকুমেন্ট এখন আরও সহজ' },
  'landing.heroNewTitle': { en: 'Every signature.', bn: 'প্রতিটি স্বাক্ষর।' },
  'landing.heroNewAccent': { en: 'One clear flow.', bn: 'একটি সহজ প্রক্রিয়া।' },
  'landing.heroNewDesc': {
    en: 'Prepare, send, sign, and track important PDFs in a workspace that keeps every person and every action clear.',
    bn: 'গুরুত্বপূর্ণ PDF প্রস্তুত করুন, পাঠান, স্বাক্ষর করুন এবং ট্র্যাক করুন। প্রতিটি ব্যক্তি ও প্রতিটি কাজ থাকবে পরিষ্কার।',
  },
  'landing.watchProduct': { en: 'See how it works', bn: 'কীভাবে কাজ করে দেখুন' },
  'landing.noInstall': { en: 'No installation', bn: 'ইনস্টল করার দরকার নেই' },
  'landing.productEyebrow': { en: 'The signing flow', bn: 'স্বাক্ষর প্রক্রিয়া' },
  'landing.productTitle': { en: 'One document. Every step in view.', bn: 'একটি ডকুমেন্ট। প্রতিটি ধাপ চোখের সামনে।' },
  'landing.productDesc': {
    en: 'Move from upload to completed signature without losing context. Explore the flow to see exactly what happens next.',
    bn: 'আপলোড থেকে সম্পূর্ণ স্বাক্ষর পর্যন্ত প্রতিটি ধাপ সহজে দেখুন। পরবর্তী কাজ কী, তা সব সময় পরিষ্কার থাকবে।',
  },
  'landing.demoUpload': { en: 'Upload', bn: 'আপলোড' },
  'landing.demoUploadCaption': { en: 'Bring in your PDF', bn: 'আপনার PDF যোগ করুন' },
  'landing.demoPrepare': { en: 'Prepare', bn: 'প্রস্তুত করুন' },
  'landing.demoPrepareCaption': { en: 'Place the right fields', bn: 'সঠিক ক্ষেত্র বসান' },
  'landing.demoInvite': { en: 'Invite', bn: 'আমন্ত্রণ' },
  'landing.demoInviteCaption': { en: 'Assign every signer', bn: 'স্বাক্ষরকারী নির্ধারণ করুন' },
  'landing.demoComplete': { en: 'Complete', bn: 'সম্পূর্ণ' },
  'landing.demoCompleteCaption': { en: 'Finish with a clear record', bn: 'সম্পূর্ণ রেকর্ড রাখুন' },
  'landing.demoDocument': { en: 'Agreement.pdf', bn: 'চুক্তিপত্র.pdf' },
  'landing.workspacePreview': { en: 'Somadhan Sign document workspace preview', bn: 'Somadhan Sign ডকুমেন্ট ওয়ার্কস্পেসের প্রিভিউ' },
  'landing.demoReady': { en: 'Ready to prepare for signing', bn: 'স্বাক্ষরের জন্য প্রস্তুত করা যাবে' },
  'landing.demoReadyStatus': { en: 'Ready', bn: 'প্রস্তুত' },
  'landing.demoDraft': { en: 'Draft', bn: 'খসড়া' },
  'landing.demoFields': { en: 'Fields', bn: 'ক্ষেত্র' },
  'landing.demoSignHere': { en: 'Sign here', bn: 'এখানে স্বাক্ষর করুন' },
  'landing.demoSignersReady': { en: 'Signers ready', bn: 'স্বাক্ষরকারীরা প্রস্তুত' },
  'landing.demoFieldsAssigned': { en: 'Each field is assigned', bn: 'প্রতিটি ক্ষেত্র নির্ধারিত' },
  'landing.demoInviteTitle': { en: 'Invite signers', bn: 'স্বাক্ষরকারী আমন্ত্রণ করুন' },
  'landing.demoInviteDesc': { en: 'Every signer gets their own fields', bn: 'প্রত্যেকে নিজের নির্ধারিত ক্ষেত্র পাবেন' },
  'landing.demoInvitationsReady': { en: 'Invitations ready', bn: 'আমন্ত্রণ প্রস্তুত' },
  'landing.demoSignedComplete': { en: 'Signed and complete', bn: 'স্বাক্ষরিত ও সম্পূর্ণ' },
  'landing.demoAuditTrail': { en: 'Audit trail', bn: 'অডিট ইতিহাস' },
  'landing.demoVerified': { en: 'Verified', bn: 'যাচাইকৃত' },
  'landing.demoDocumentCreated': { en: 'Document created', bn: 'ডকুমেন্ট তৈরি হয়েছে' },
  'landing.demoInvitationsDelivered': { en: 'Invitations delivered', bn: 'আমন্ত্রণ পৌঁছেছে' },
  'landing.demoAllSigned': { en: 'All signatures completed', bn: 'সব স্বাক্ষর সম্পন্ন' },
  'landing.capabilityEyebrow': { en: 'Built for real documents', bn: 'বাস্তব ডকুমেন্টের জন্য' },
  'landing.capabilityTitle': { en: 'Less friction at every handoff.', bn: 'প্রতিটি ধাপে কম ঝামেলা।' },
  'landing.capabilityDesc': {
    en: 'Somadhan Sign keeps preparation simple for senders and makes the final signing experience obvious for everyone else.',
    bn: 'সমাধান সাইন প্রেরকের প্রস্তুতি সহজ রাখে এবং অন্য সবার জন্য স্বাক্ষরের অভিজ্ঞতা পরিষ্কার করে।',
  },
  'landing.securityEyebrow': { en: 'Clarity and control', bn: 'স্বচ্ছতা ও নিয়ন্ত্রণ' },
  'landing.securityTitle': { en: 'Know what happened to every document.', bn: 'প্রতিটি ডকুমেন্টের কার্যক্রম জানুন।' },
  'landing.securityDesc': {
    en: 'Follow document activity, signer progress, and final completion from one place with a detailed audit history.',
    bn: 'একটি বিস্তারিত অডিট ইতিহাসের মাধ্যমে ডকুমেন্ট কার্যক্রম, স্বাক্ষরকারীর অগ্রগতি এবং সম্পূর্ণ অবস্থা দেখুন।',
  },
  'landing.securityItem1': { en: 'Signer-specific fields', bn: 'স্বাক্ষরকারীভিত্তিক ক্ষেত্র' },
  'landing.securityItem2': { en: 'Status tracking', bn: 'স্ট্যাটাস ট্র্যাকিং' },
  'landing.securityItem3': { en: 'Detailed audit history', bn: 'বিস্তারিত অডিট ইতিহাস' },
  'landing.securityItem4': { en: 'Completed PDF export', bn: 'সম্পূর্ণ PDF এক্সপোর্ট' },
  'landing.ctaEyebrow': { en: 'Your next document', bn: 'আপনার পরবর্তী ডকুমেন্ট' },
  'landing.ctaNewTitle': { en: 'Ready when you are.', bn: 'আপনি প্রস্তুত, আমরাও প্রস্তুত।' },
  'landing.ctaNewDesc': { en: 'Create your account and send your first document for signing.', bn: 'অ্যাকাউন্ট তৈরি করুন এবং আপনার প্রথম ডকুমেন্ট স্বাক্ষরের জন্য পাঠান।' },
  'landing.getStartedFree': { en: 'Get Started Free', bn: 'বিনামূল্যে শুরু করুন' },
  'landing.signIn': { en: 'Sign In', bn: 'সাইন ইন' },
  'landing.howItWorks': { en: 'How it works', bn: 'কিভাবে কাজ করে?' },
  'landing.howItWorksDesc': {
    en: 'Get documents signed in four simple steps',
    bn: 'চারটি সহজ ধাপে ডকুমেন্ট স্বাক্ষর করুন',
  },
  'landing.step1Title': { en: 'Upload your PDF', bn: 'আপনার PDF আপলোড করুন' },
  'landing.step1Desc': { en: 'Drag and drop or browse to upload', bn: 'টেনে আনুন বা ব্রাউজ করে আপলোড করুন' },
  'landing.step2Title': { en: 'Define signature fields', bn: 'স্বাক্ষর ক্ষেত্র নির্ধারণ করুন' },
  'landing.step2Desc': { en: 'Click on the PDF to place fields', bn: 'ক্ষেত্র রাখতে PDF-এ ক্লিক করুন' },
  'landing.step3Title': { en: 'Assign signers', bn: 'স্বাক্ষরকারী নির্ধারণ করুন' },
  'landing.step3Desc': { en: 'Add emails and assign fields to each signer', bn: 'ইমেইল যোগ করুন এবং প্রতিটি স্বাক্ষরকারীকে ক্ষেত্র নির্ধারণ করুন' },
  'landing.step4Title': { en: 'Send for signing', bn: 'স্বাক্ষরের জন্য পাঠান' },
  'landing.step4Desc': { en: 'Signers receive an email with a link', bn: 'স্বাক্ষরকারীরা লিঙ্ক সহ একটি ইমেইল পাবেন' },
  'landing.everything': { en: 'Everything you need', bn: 'আপনার যা দরকার সবকিছু' },
  'landing.everythingDesc': {
    en: 'Powerful features to handle any document signing workflow',
    bn: 'যেকোনো ডকুমেন্ট স্বাক্ষর কর্মপ্রবাহ পরিচালনার জন্য শক্তিশালী ফিচার',
  },
  'landing.feat.upload': { en: 'Upload Documents', bn: 'ডকুমেন্ট আপলোড' },
  'landing.feat.uploadDesc': {
    en: 'Upload any PDF document and prepare it for signing in seconds.',
    bn: 'যেকোনো PDF ডকুমেন্ট আপলোড করুন এবং কয়েক সেকেন্ডে স্বাক্ষরের জন্য প্রস্তুত করুন।',
  },
  'landing.feat.fields': { en: 'Place Signature Fields', bn: 'স্বাক্ষর ক্ষেত্র রাখুন' },
  'landing.feat.fieldsDesc': {
    en: 'Drag and drop signature fields anywhere on the document. Assign each field to a specific signer.',
    bn: 'ডকুমেন্টের যেকোনো জায়গায় স্বাক্ষর ক্ষেত্র টেনে আনুন। প্রতিটি ক্ষেত্র একজন নির্দিষ্ট স্বাক্ষরকারীকে নির্ধারণ করুন।',
  },
  'landing.feat.multi': { en: 'Multi-Party Signing', bn: 'মাল্টি-পার্টি স্বাক্ষর' },
  'landing.feat.multiDesc': {
    en: 'Invite multiple signers. Each signer sees only their assigned fields with guided navigation.',
    bn: 'একাধিক স্বাক্ষরকারী আমন্ত্রণ করুন। প্রতিটি স্বাক্ষরকারী শুধু তাদের নির্ধারিত ক্ষেত্র দেখবেন।',
  },
  'landing.feat.track': { en: 'Send & Track', bn: 'পাঠান ও ট্র্যাক করুন' },
  'landing.feat.trackDesc': {
    en: 'Send documents for signing and track progress from your dashboard.',
    bn: 'স্বাক্ষরের জন্য ডকুমেন্ট পাঠান এবং ড্যাশবোর্ড থেকে অগ্রগতি ট্র্যাক করুন।',
  },
  'landing.feat.secure': { en: 'Controlled Access', bn: 'নিয়ন্ত্রিত অ্যাক্সেস' },
  'landing.feat.secureDesc': {
    en: 'Unique signer links and a detailed activity history make document access and events easier to track.',
    bn: 'অনন্য স্বাক্ষর লিঙ্ক ও বিস্তারিত কার্যক্রমের ইতিহাস ডকুমেন্ট অ্যাক্সেস এবং ঘটনাগুলো ট্র্যাক করা সহজ করে।',
  },
  'landing.feat.anywhere': { en: 'Sign Anywhere', bn: 'যেকোনো জায়গায় সাইন করুন' },
  'landing.feat.anywhereDesc': {
    en: 'Draw, type, or upload your signature. Sign all fields at once or one by one.',
    bn: 'আপনার স্বাক্ষর আঁকুন, টাইপ করুন বা আপলোড করুন। একসাথে বা একটি একটি করে সব ক্ষেত্রে সাইন করুন।',
  },
  'landing.ctaTitle': { en: 'Ready to get started?', bn: 'শুরু করতে প্রস্তুত?' },
  'landing.ctaDesc': {
    en: 'Create an account and start preparing your first document.',
    bn: 'অ্যাকাউন্ট তৈরি করুন এবং আপনার প্রথম ডকুমেন্ট প্রস্তুত করুন।',
  },
  'landing.createFreeAccount': { en: 'Create Free Account', bn: 'বিনামূল্যে অ্যাকাউন্ট তৈরি করুন' },
  'landing.freeToStart': { en: 'Free to start', bn: 'বিনামূল্যে শুরু' },
  'landing.noCreditCard': { en: 'No credit card', bn: 'ক্রেডিট কার্ড লাগবে না' },
  'landing.unlimitedDocs': { en: 'Unlimited documents', bn: 'সীমাহীন ডকুমেন্ট' },
  'landing.footer': { en: 'Somadhan. All rights reserved.', bn: 'সমাধান। সর্বস্বত্ব সংরক্ষিত।' },

  // ─── Login Page ───
  'login.welcomeBack': { en: 'Welcome back', bn: 'স্বাগতম' },
  'login.signInToContinue': { en: 'Sign in to your account to continue', bn: 'চালিয়ে যেতে আপনার অ্যাকাউন্টে সাইন ইন করুন' },
  'login.continueWithGoogle': { en: 'Continue with Google', bn: 'গুগল দিয়ে চালিয়ে যান' },
  'login.orContinueWithEmail': { en: 'OR CONTINUE WITH EMAIL', bn: 'অথবা ইমেইল দিয়ে চালিয়ে যান' },
  'login.email': { en: 'Email', bn: 'ইমেইল' },
  'login.password': { en: 'Password', bn: 'পাসওয়ার্ড' },
  'login.fullName': { en: 'Full Name', bn: 'পুরো নাম' },
  'login.signIn': { en: 'Sign In', bn: 'সাইন ইন' },
  'login.signUp': { en: 'Sign Up', bn: 'সাইন আপ' },
  'login.forgotPassword': { en: 'Forgot password?', bn: 'পাসওয়ার্ড ভুলে গেছেন?' },
  'login.noAccount': { en: "Don't have an account?", bn: 'অ্যাকাউন্ট নেই?' },
  'login.hasAccount': { en: 'Already have an account?', bn: 'ইতিমধ্যে অ্যাকাউন্ট আছে?' },
  'login.signUpLink': { en: 'Sign up', bn: 'সাইন আপ করুন' },
  'login.signInLink': { en: 'Sign in', bn: 'সাইন ইন করুন' },
  'login.createAccount': { en: 'Create account', bn: 'অ্যাকাউন্ট তৈরি করুন' },
  'login.createAccountDesc': { en: 'Enter your details to get started', bn: 'শুরু করতে আপনার তথ্য দিন' },
  'login.resetPassword': { en: 'Reset your password', bn: 'পাসওয়ার্ড রিসেট করুন' },
  'login.resetPasswordDesc': {
    en: "Enter your email and we'll send you a password reset link",
    bn: 'আপনার ইমেইল দিন এবং আমরা পাসওয়ার্ড রিসেট লিঙ্ক পাঠাব',
  },
  'login.sendResetLink': { en: 'Send Reset Link', bn: 'রিসেট লিঙ্ক পাঠান' },
  'login.alreadyRegistered': {
    en: 'This email is already registered. Please login with your password or use "Forgot password" to reset it. If you signed up with Google, use "Continue with Google" instead.',
    bn: 'এই ইমেইলটি ইতিমধ্যে নিবন্ধিত। অনুগ্রহ করে আপনার পাসওয়ার্ড দিয়ে লগইন করুন অথবা "পাসওয়ার্ড ভুলে গেছেন?" ব্যবহার করুন। আপনি যদি Google দিয়ে সাইন আপ করে থাকেন, তাহলে "Google দিয়ে চালিয়ে যান" ব্যবহার করুন।',
  },
  'login.backToSignIn': { en: 'Back to sign in', bn: 'সাইন ইন-এ ফিরে যান' },
  'login.verifyEmail': { en: 'Verify your email', bn: 'আপনার ইমেইল যাচাই করুন' },
  'login.verifyEmailDesc': { en: 'Enter the 6-digit code sent to', bn: '৬ সংখ্যার কোড দিন যা পাঠানো হয়েছে' },
  'login.verifyCode': { en: 'Verify Code', bn: 'কোড যাচাই করুন' },
  'login.resendCode': { en: 'Resend Code', bn: 'কোড পুনরায় পাঠান' },
  'login.signingIn': { en: 'Signing in...', bn: 'সাইন ইন হচ্ছে...' },
  'login.creatingAccount': { en: 'Creating account...', bn: 'অ্যাকাউন্ট তৈরি হচ্ছে...' },
  'login.sendingResetLink': { en: 'Sending reset link...', bn: 'রিসেট লিঙ্ক পাঠানো হচ্ছে...' },
  'login.verifyingCode': { en: 'Verifying code...', bn: 'কোড যাচাই করা হচ্ছে...' },
  'login.verificationSent': { en: 'If this email can be registered, a 6-digit verification code is on its way.', bn: 'এই ইমেইল নিবন্ধন করা গেলে ৬ সংখ্যার যাচাইকরণ কোড পাঠানো হচ্ছে।' },
  'login.resetLinkSent': { en: 'Password reset link has been sent to your email. Please check your inbox.', bn: 'পাসওয়ার্ড রিসেট লিঙ্ক আপনার ইমেইলে পাঠানো হয়েছে। ইনবক্স দেখুন।' },
  'login.genericError': { en: 'Something went wrong. Please try again.', bn: 'কিছু সমস্যা হয়েছে। আবার চেষ্টা করুন।' },
  'login.googleStartFailed': { en: 'Google sign-in could not be started. Please try again.', bn: 'Google সাইন ইন শুরু করা যায়নি। আবার চেষ্টা করুন।' },
  'login.tooManyAttempts': { en: 'Too many attempts. Please try again in {minutes} minutes.', bn: 'অনেকবার চেষ্টা করা হয়েছে। {minutes} মিনিট পর আবার চেষ্টা করুন।' },
  'login.otpBlocked': { en: 'Too many verification-code attempts. Try again in 1 hour.', bn: 'যাচাইকরণ কোড অনেকবার চেষ্টা করা হয়েছে। ১ ঘণ্টা পর আবার চেষ্টা করুন।' },
  'login.newOtpSent': { en: 'New verification code sent. Check your email.', bn: 'নতুন যাচাইকরণ কোড পাঠানো হয়েছে। ইমেইল দেখুন।' },
  'login.resendFailed': { en: 'The verification code could not be resent. Please try again.', bn: 'যাচাইকরণ কোড আবার পাঠানো যায়নি। আবার চেষ্টা করুন।' },
  'login.otpLabel': { en: '6-digit verification code', bn: '৬ সংখ্যার যাচাইকরণ কোড' },
  'login.didNotReceiveCode': { en: "Didn't receive the code?", bn: 'কোড পাননি?' },
  'login.resendOtp': { en: 'Resend code', bn: 'কোড আবার পাঠান' },
  'login.resendOtpCountdown': { en: 'Resend code ({seconds}s)', bn: 'কোড আবার পাঠান ({seconds} সেকেন্ড)' },
  'login.backToSignup': { en: 'Back to sign up', bn: 'সাইন আপে ফিরে যান' },
  'login.namePlaceholder': { en: 'John Doe', bn: 'রহিম আহমেদ' },
  'login.showPassword': { en: 'Show password', bn: 'পাসওয়ার্ড দেখান' },
  'login.hidePassword': { en: 'Hide password', bn: 'পাসওয়ার্ড লুকান' },
  'login.passwordHint': { en: 'Use at least 8 characters.', bn: 'কমপক্ষে ৮ অক্ষর ব্যবহার করুন।' },
  'login.passwordPlaceholder': { en: 'Enter your password', bn: 'আপনার পাসওয়ার্ড লিখুন' },
  'login.brandingTitle': { en: 'Sign documents with', bn: 'ডকুমেন্ট সাইন করুন' },
  'login.brandingDesc': {
    en: 'Upload, define signature fields, invite signers, and get documents signed in one place.',
    bn: 'আপলোড করুন, স্বাক্ষর ক্ষেত্র নির্ধারণ করুন, স্বাক্ষরকারী আমন্ত্রণ করুন এবং এক জায়গায় ডকুমেন্ট সাইন করুন।',
  },
  'login.brandingEyebrow': { en: 'A clearer way to sign', bn: 'স্বাক্ষরের আরও সহজ উপায়' },
  'login.brandingNewTitle1': { en: 'Your document.', bn: 'আপনার ডকুমেন্ট।' },
  'login.brandingNewTitle2': { en: 'Ready for everyone.', bn: 'সবার জন্য প্রস্তুত।' },
  'login.statDocuments': { en: 'Documents', bn: 'ডকুমেন্ট' },
  'login.statUsers': { en: 'Users', bn: 'ব্যবহারকারী' },
  'login.statUptime': { en: 'Uptime', bn: 'আপটাইম' },
  'login.copyright': { en: 'Somadhan. All rights reserved.', bn: 'সমাধান। সর্বস্বত্ব সংরক্ষিত।' },
  'login.accountVerified': { en: 'Account Verified!', bn: 'অ্যাকাউন্ট যাচাই হয়েছে!' },
  'login.accountVerifiedDesc': {
    en: 'Your email has been confirmed. You can now use SomadhanSign.',
    bn: 'আপনার ইমেইল নিশ্চিত হয়েছে। আপনি এখন সমাধান সাইন ব্যবহার করতে পারেন।',
  },
  'login.letsGo': { en: "OK, Let's Go!", bn: 'চলুন শুরু করি!' },

  // ─── Password Reset ───
  'reset.setNewPassword': { en: 'Set New Password', bn: 'নতুন পাসওয়ার্ড সেট করুন' },
  'reset.enterNewPassword': { en: 'Enter your new password below', bn: 'নিচে আপনার নতুন পাসওয়ার্ড দিন' },
  'reset.validatingLink': { en: 'Validating your secure reset link...', bn: 'আপনার নিরাপদ রিসেট লিংক যাচাই করা হচ্ছে...' },
  'reset.newPassword': { en: 'New Password', bn: 'নতুন পাসওয়ার্ড' },
  'reset.confirmPassword': { en: 'Confirm Password', bn: 'পাসওয়ার্ড নিশ্চিত করুন' },
  'reset.updatePassword': { en: 'Update Password', bn: 'পাসওয়ার্ড আপডেট করুন' },
  'reset.updatingPassword': { en: 'Updating password...', bn: 'পাসওয়ার্ড আপডেট হচ্ছে...' },
  'reset.passwordUpdated': { en: 'Password Updated!', bn: 'পাসওয়ার্ড আপডেট হয়েছে!' },
  'reset.passwordUpdatedDesc': {
    en: 'Your password has been successfully reset. You can now sign in with your new password.',
    bn: 'আপনার পাসওয়ার্ড সফলভাবে রিসেট হয়েছে। এখন আপনি নতুন পাসওয়ার্ড দিয়ে সাইন ইন করতে পারেন।',
  },
  'reset.goToLogin': { en: 'Go to Login', bn: 'লগইন পেজে যান' },
  'reset.backToLogin': { en: 'Back to Login', bn: 'লগইনে ফিরে যান' },
  'reset.passwordTooShort': { en: 'Password must be at least 8 characters.', bn: 'পাসওয়ার্ড কমপক্ষে ৮ অক্ষরের হতে হবে।' },
  'reset.passwordsDoNotMatch': { en: 'Passwords do not match.', bn: 'পাসওয়ার্ড মিলছে না।' },
  'reset.linkExpired': {
    en: 'This password reset link has expired or is invalid. Please request a new one.',
    bn: 'এই পাসওয়ার্ড রিসেট লিঙ্কটি মেয়াদ শেষ হয়েছে বা অবৈধ। অনুগ্রহ করে নতুন একটি অনুরোধ করুন।',
  },
  'reset.errorOccurred': { en: 'An error occurred. Please try again.', bn: 'একটি ত্রুটি ঘটেছে। আবার চেষ্টা করুন।' },
  'reset.failedToUpdate': { en: 'Failed to update password', bn: 'পাসওয়ার্ড আপডেট করতে ব্যর্থ' },

  // ─── Dashboard ───
  'dashboard.myDocuments': { en: 'My Documents', bn: 'আমার ডকুমেন্টস' },
  'dashboard.newDocument': { en: 'New Document', bn: 'নতুন ডকুমেন্ট' },
  'dashboard.searchDocs': { en: 'Search documents...', bn: 'ডকুমেন্ট খুঁজুন...' },
  'dashboard.noDocuments': { en: 'No documents yet', bn: 'এখনো কোনো ডকুমেন্ট নেই' },
  'dashboard.noMatches': { en: 'No matching documents', bn: 'মিলে যাওয়া কোনো ডকুমেন্ট নেই' },
  'dashboard.adjustFilters': { en: 'Try another search or status filter.', bn: 'অন্য কিছু খুঁজুন বা স্ট্যাটাস ফিল্টার পরিবর্তন করুন।' },
  'dashboard.clearFilters': { en: 'Clear filters', bn: 'ফিল্টার মুছুন' },
  'dashboard.backToDashboard': { en: 'Back to dashboard', bn: 'ড্যাশবোর্ডে ফিরে যান' },
  'dashboard.allSignersDone': { en: 'All signers done', bn: 'সব স্বাক্ষরকারী সম্পন্ন করেছেন' },
  'dashboard.signers': { en: 'Signers', bn: 'স্বাক্ষরকারী' },
  'dashboard.signed': { en: 'Signed', bn: 'স্বাক্ষরিত' },
  'dashboard.viewed': { en: 'Viewed', bn: 'দেখেছেন' },
  'dashboard.viewAuditTrail': { en: 'View audit trail', bn: 'অডিট ইতিহাস দেখুন' },
  'dashboard.preparing': { en: 'Preparing...', bn: 'প্রস্তুত হচ্ছে...' },
  'dashboard.downloading': { en: 'Downloading...', bn: 'ডাউনলোড হচ্ছে...' },
  'dashboard.downloadSignedPdf': { en: 'Download signed PDF', bn: 'স্বাক্ষরিত PDF ডাউনলোড করুন' },
  'dashboard.downloadOriginalPdf': { en: 'Download original PDF', bn: 'মূল PDF ডাউনলোড করুন' },
  'dashboard.documentUnavailable': { en: 'The document could not be found or is no longer available.', bn: 'ডকুমেন্টটি পাওয়া যায়নি বা আর উপলভ্য নেই।' },
  'dashboard.signedDownloadFailed': { en: 'The signed PDF could not be prepared. Please try again.', bn: 'স্বাক্ষরিত PDF প্রস্তুত করা যায়নি। আবার চেষ্টা করুন।' },
  'dashboard.originalDownloadFailed': { en: 'The original PDF could not be downloaded. Please try again.', bn: 'মূল PDF ডাউনলোড করা যায়নি। আবার চেষ্টা করুন।' },
  'dashboard.uploadFirst': {
    en: 'Upload your first PDF to get started',
    bn: 'শুরু করতে আপনার প্রথম PDF আপলোড করুন',
  },
  'dashboard.uploadPdf': { en: 'Upload PDF', bn: 'PDF আপলোড করুন' },
  'dashboard.draft': { en: 'Draft', bn: 'খসড়া' },
  'dashboard.pending': { en: 'Pending', bn: 'অপেক্ষমাণ' },
  'dashboard.completed': { en: 'Completed', bn: 'সম্পন্ন' },
  'dashboard.cancelled': { en: 'Cancelled', bn: 'বাতিল' },
  'dashboard.delete': { en: 'Delete', bn: 'মুছুন' },
  'dashboard.edit': { en: 'Edit', bn: 'সম্পাদনা' },
  'dashboard.view': { en: 'View', bn: 'দেখুন' },
  'dashboard.sendReminder': { en: 'Send Reminder', bn: 'রিমাইন্ডার পাঠান' },
  'dashboard.total': { en: 'Total', bn: 'মোট' },
  'dashboard.drafts': { en: 'Drafts', bn: 'খসড়া' },
  'dashboard.all': { en: 'All', bn: 'সব' },
  'dashboard.download': { en: 'Download', bn: 'ডাউনলোড' },
  'dashboard.auditTrail': { en: 'Audit Trail', bn: 'অডিট ট্রেইল' },
  'dashboard.deleteDocument': { en: 'Delete Document', bn: 'ডকুমেন্ট মুছুন' },
  'dashboard.deleteConfirmMessage': { en: 'Delete', bn: 'মুছুন' },
  'dashboard.cannotUndo': { en: 'This cannot be undone.', bn: 'এটি পূর্বাবস্থায় ফেরানো যাবে না।' },
  'dashboard.enterTitle': { en: 'Enter a document title.', bn: 'ডকুমেন্টের শিরোনাম লিখুন।' },
  'dashboard.titleTooLong': { en: 'Use 160 characters or fewer for the document title.', bn: 'ডকুমেন্টের শিরোনাম ১৬০ অক্ষর বা তার কম রাখুন।' },
  'dashboard.loadingDocuments': { en: 'Loading documents...', bn: 'ডকুমেন্ট লোড হচ্ছে...' },
  'dashboard.documentsLoadFailed': { en: 'Your documents could not be loaded', bn: 'আপনার ডকুমেন্টগুলো লোড করা যায়নি' },
  'dashboard.documentsLoadFailedDesc': {
    en: 'Your files have not been removed. Check your connection and try loading them again.',
    bn: 'আপনার ফাইলগুলো মুছে যায়নি। সংযোগ পরীক্ষা করে আবার লোড করার চেষ্টা করুন।',
  },
  'dashboard.uploadFailed': { en: 'The document could not be uploaded. Check your connection and try again.', bn: 'ডকুমেন্ট আপলোড করা যায়নি। সংযোগ পরীক্ষা করে আবার চেষ্টা করুন।' },
  'dashboard.loadingSigners': { en: 'Loading signers...', bn: 'স্বাক্ষরকারীদের লোড করা হচ্ছে...' },
  'dashboard.signersLoadFailed': { en: 'Signer details could not be loaded.', bn: 'স্বাক্ষরকারীর বিস্তারিত লোড করা যায়নি।' },
  'dashboard.noSigners': { en: 'No signers', bn: 'কোনো স্বাক্ষরকারী নেই' },
  'dashboard.reminderSentTo': { en: 'Reminder sent to', bn: 'রিমাইন্ডার পাঠানো হয়েছে' },
  'dashboard.pendingSigner': { en: 'pending signer', bn: 'জন অপেক্ষমাণ স্বাক্ষরকারীকে' },
  'dashboard.pendingSigners': { en: 'pending signers', bn: 'জন অপেক্ষমাণ স্বাক্ষরকারীকে' },
  'dashboard.failedCount': { en: 'failed', bn: 'টি ব্যর্থ হয়েছে' },
  'dashboard.reminderFailed': { en: 'The reminder could not be sent. Please try again.', bn: 'রিমাইন্ডার পাঠানো যায়নি। আবার চেষ্টা করুন।' },
  'dashboard.noPendingSigners': { en: 'No pending signers to remind.', bn: 'রিমাইন্ডার দেওয়ার মতো অপেক্ষমাণ স্বাক্ষরকারী নেই।' },
  'dashboard.completedPdfFailed': { en: 'The completed PDF could not be generated. Please try again.', bn: 'সম্পন্ন PDF তৈরি করা যায়নি। আবার চেষ্টা করুন।' },
  'dashboard.showingDocuments': { en: 'Showing {start}-{end} of {total} documents', bn: 'মোট {total}টি ডকুমেন্টের মধ্যে {start}-{end} দেখানো হচ্ছে' },
  'dashboard.pageOf': { en: 'Page {page} of {total}', bn: 'পৃষ্ঠা {page}, মোট {total}' },
  'dashboard.previous': { en: 'Previous', bn: 'আগের' },
  'dashboard.next': { en: 'Next', bn: 'পরের' },
  'dashboard.uploadDocument': { en: 'Upload Document', bn: 'ডকুমেন্ট আপলোড করুন' },
  'dashboard.documentTitle': { en: 'Document Title', bn: 'ডকুমেন্টের শিরোনাম' },
  'dashboard.documentTitlePlaceholder': { en: 'e.g. Contract Agreement', bn: 'যেমন: চুক্তিপত্র' },
  'dashboard.pdfFile': { en: 'PDF File', bn: 'PDF ফাইল' },
  'dashboard.clickUploadPdf': { en: 'Click to upload PDF', bn: 'PDF আপলোড করতে ক্লিক করুন' },
  'dashboard.pdfLimit': { en: 'PDF files up to 5 MB', bn: 'সর্বোচ্চ ৫ MB PDF ফাইল' },
  'dashboard.uploadAndContinue': { en: 'Upload and Continue', bn: 'আপলোড করে এগিয়ে যান' },
  'dashboard.uploading': { en: 'Uploading...', bn: 'আপলোড হচ্ছে...' },
  'dashboard.createdOn': { en: 'Created {date}', bn: 'তৈরি হয়েছে {date}' },
  'dashboard.showSignersFor': { en: 'Show signers for {title}', bn: '{title} এর স্বাক্ষরকারীদের দেখান' },
  'dashboard.hideSignersFor': { en: 'Hide signers for {title}', bn: '{title} এর স্বাক্ষরকারীদের লুকান' },
  'dashboard.openActionsFor': { en: 'Open actions for {title}', bn: '{title} এর কাজগুলো খুলুন' },
  'dashboard.documentDeleted': { en: 'Document deleted.', bn: 'ডকুমেন্ট মুছে ফেলা হয়েছে।' },
  'dashboard.deleteFailed': { en: 'The document could not be deleted. Please try again.', bn: 'ডকুমেন্ট মুছে ফেলা যায়নি। আবার চেষ্টা করুন।' },
  'dashboard.confirm': { en: 'OK', bn: 'ঠিক আছে' },
  'dashboard.pdfEmpty': { en: 'The selected PDF is empty.', bn: 'নির্বাচিত PDF ফাইলটি খালি।' },
  'dashboard.pdfTooLarge': { en: 'The PDF must be 5 MB or smaller.', bn: 'PDF ফাইলটি ৫ MB বা তার কম হতে হবে।' },
  'dashboard.pdfRequired': { en: 'Please select a PDF file.', bn: 'একটি PDF ফাইল নির্বাচন করুন।' },
  'dashboard.pdfInvalidHeader': { en: 'This file does not contain a valid PDF header.', bn: 'এই ফাইলটিতে বৈধ PDF হেডার নেই।' },
  'dashboard.pdfUnsupported': { en: 'The PDF is damaged, encrypted, or unsupported.', bn: 'PDF ফাইলটি ক্ষতিগ্রস্ত, এনক্রিপ্ট করা, অথবা সমর্থিত নয়।' },
  'dashboard.pdfNoPages': { en: 'The PDF does not contain any pages.', bn: 'PDF ফাইলটিতে কোনো পৃষ্ঠা নেই।' },
  'dashboard.pdfUnsafeContent': {
    en: 'This PDF contains active content or attachments that cannot be signed safely.',
    bn: 'এই PDF-এ সক্রিয় কনটেন্ট বা সংযুক্তি আছে, তাই এটি নিরাপদভাবে স্বাক্ষর করা যাবে না।',
  },

  // ─── Document Editor ───
  'editor.signers': { en: 'Signers', bn: 'স্বাক্ষরকারী' },
  'editor.addSigner': { en: 'Add Signer', bn: 'স্বাক্ষরকারী যোগ করুন' },
  'editor.fields': { en: 'Fields', bn: 'ক্ষেত্র' },
  'editor.signature': { en: 'Signature', bn: 'স্বাক্ষর' },
  'editor.initials': { en: 'Initials', bn: 'ইনিশিয়াল' },
  'editor.date': { en: 'Date', bn: 'তারিখ' },
  'editor.checkbox': { en: 'Checkbox', bn: 'চেকবক্স' },
  'editor.text': { en: 'Text', bn: 'টেক্সট' },
  'editor.saveDraft': { en: 'Save Draft', bn: 'খসড়া সংরক্ষণ' },
  'editor.saving': { en: 'Saving...', bn: 'সংরক্ষণ হচ্ছে...' },
  'editor.saved': { en: 'All changes saved', bn: 'সব পরিবর্তন সংরক্ষিত' },
  'editor.autosaveFailed': { en: 'Changes are not saved. Check your connection and try again.', bn: 'পরিবর্তন সংরক্ষিত হয়নি। সংযোগ পরীক্ষা করে আবার চেষ্টা করুন।' },
  'editor.sendForSigning': { en: 'Send for Signing', bn: 'স্বাক্ষরের জন্য পাঠান' },
  'editor.locked': { en: 'Document sent - editing locked', bn: 'ডকুমেন্ট পাঠানো হয়েছে - সম্পাদনা লক' },
  'editor.helpTitle': { en: 'Quick Guide', bn: 'দ্রুত নির্দেশিকা' },
  'editor.help1': {
    en: '1. Add signers using the + button above',
    bn: '১. উপরের + বাটন ব্যবহার করে স্বাক্ষরকারী যোগ করুন',
  },
  'editor.help2': {
    en: '2. Select a field type below (Signature, Initials, etc.)',
    bn: '২. নিচে একটি ক্ষেত্রের ধরন নির্বাচন করুন (স্বাক্ষর, ইনিশিয়াল, ইত্যাদি)',    
  },
  'editor.help3': {
    en: '3. Click on the PDF to place the field',
    bn: '৩. ক্ষেত্র রাখতে PDF-এ ক্লিক করুন',
  },
  'editor.help4': {
    en: '4. Click a placed field to assign it to a signer',
    bn: '৪. একটি রাখা ক্ষেত্রে ক্লিক করে স্বাক্ষরকারী নির্ধারণ করুন',
  },
  'editor.help5': {
    en: '5. Changes save automatically. Send when ready',
    bn: '৫. পরিবর্তন স্বয়ংক্রিয়ভাবে সংরক্ষিত হবে। প্রস্তুত হলে পাঠান',
  },
  'editor.clickFieldHint': {
    en: 'Click a field on the PDF to see its details and change the assigned signer.',
    bn: 'ক্ষেত্রের বিস্তারিত দেখতে এবং নির্ধারিত স্বাক্ষরকারী পরিবর্তন করতে PDF-এ একটি ক্ষেত্রে ক্লিক করুন।',
  },
  'editor.addSignerFirst': { en: 'Please add at least one signer first.', bn: 'অনুগ্রহ করে প্রথমে কমপক্ষে একজন স্বাক্ষরকারী যোগ করুন।' },
  'editor.assignAllFields': { en: 'Please assign all fields to a signer before sending.', bn: 'পাঠানোর আগে সকল ক্ষেত্র একজন স্বাক্ষরকারীকে নির্ধারণ করুন।' },
  'editor.addSignerRequired': { en: 'Please add at least one signer.', bn: 'অনুগ্রহ করে কমপক্ষে একজন স্বাক্ষরকারী যোগ করুন।' },
  'editor.addFieldRequired': { en: 'Please add at least one field to the document.', bn: 'অনুগ্রহ করে ডকুমেন্টে কমপক্ষে একটি ক্ষেত্র যোগ করুন।' },
  'editor.signatureFieldRequired': { en: 'Please add at least one Signature field for', bn: 'অনুগ্রহ করে কমপক্ষে একটি স্বাক্ষর ক্ষেত্র যোগ করুন' },
  'editor.everySignerMustHaveSignature': { en: 'Every signer must have a signature field.', bn: 'প্রত্যেক স্বাক্ষরকারীর একটি স্বাক্ষর ক্ষেত্র থাকতে হবে।' },
  'editor.cannotDeleteSigned': { en: 'Cannot delete this field - it has already been signed by a signer.', bn: 'এই ক্ষেত্রটি মুছতে পারবেন না - এটি ইতিমধ্যে স্বাক্ষরিত হয়েছে।' },
  'editor.removeSignerConfirm': { en: 'Remove this signer and all their fields?', bn: 'এই স্বাক্ষরকারী এবং তাদের সকল ক্ষেত্র মুছবেন?' },
  'editor.removeSigner': { en: 'Remove Signer', bn: 'স্বাক্ষরকারী মুছুন' },
  'editor.failedSaveSigner': { en: 'Failed to save signer. Please try again.', bn: 'স্বাক্ষরকারী সংরক্ষণ করতে ব্যর্থ। আবার চেষ্টা করুন।' },
  'editor.invalidEmail': { en: 'Please enter a valid email address.', bn: 'অনুগ্রহ করে একটি সঠিক ইমেইল ঠিকানা দিন।' },
  'editor.duplicateEmail': { en: 'This email is already included on this document.', bn: 'এই ইমেইলটি ইতিমধ্যে এই ডকুমেন্টে যোগ করা হয়েছে।' },
  'editor.error': { en: 'Error', bn: 'ত্রুটি' },
  'editor.validation': { en: 'Validation', bn: 'যাচাইকরণ' },
  'editor.addSignerFirstDesc': { en: 'You need to add at least one signer before placing fields on the document.', bn: 'ডকুমেন্টে ক্ষেত্র রাখার আগে আপনাকে কমপক্ষে একজন স্বাক্ষরকারী যোগ করতে হবে।' },
  'editor.editSigner': { en: 'Edit Signer', bn: 'স্বাক্ষরকারী সম্পাদনা করুন' },
  'editor.sendForSigningTitle': { en: 'Send for Signing', bn: 'স্বাক্ষরের জন্য পাঠান' },
  'editor.sendingDocument': { en: 'Sending Document...', bn: 'ডকুমেন্ট পাঠানো হচ্ছে...' },
  'editor.pleaseWait': { en: 'Please wait while we send emails to signers.', bn: 'স্বাক্ষরকারীদের ইমেইল পাঠানোর সময় অপেক্ষা করুন।' },
  'editor.documentSent': { en: 'Document Sent!', bn: 'ডকুমেন্ট পাঠানো হয়েছে!' },
  'editor.signersWillReceive': { en: 'Signers will receive emails shortly.', bn: 'স্বাক্ষরকারীরা শীঘ্রই ইমেইল পাবেন।' },
  'editor.redirecting': { en: 'Redirecting to dashboard in', bn: 'ড্যাশবোর্ডে রিডাইরেক্ট করা হচ্ছে' },
  'editor.close': { en: 'Close', bn: 'বন্ধ করুন' },
  'editor.firstName': { en: 'First Name', bn: 'প্রথম নাম' },
  'editor.lastName': { en: 'Last Name', bn: 'শেষ নাম' },
  'editor.email': { en: 'Email', bn: 'ইমেইল' },
  'editor.cancel': { en: 'Cancel', bn: 'বাতিল' },
  'editor.saveChanges': { en: 'Save Changes', bn: 'পরিবর্তন সংরক্ষণ করুন' },
  'editor.documentName': { en: 'Document Name', bn: 'ডকুমেন্টের নাম' },
  'editor.ccEmail': { en: 'CC: Email a copy (optional)', bn: 'CC: একটি কপি ইমেইল করুন (ঐচ্ছিক)' },
  'editor.messageForSignees': { en: 'Message for signees (optional)', bn: 'স্বাক্ষরকারীদের জন্য বার্তা (ঐচ্ছিক)' },
  'editor.sending': { en: 'Sending...', bn: 'পাঠানো হচ্ছে...' },
  'editor.send': { en: 'Send', bn: 'পাঠান' },
  'editor.savedSuccess': { en: 'Document saved successfully', bn: 'ডকুমেন্ট সফলভাবে সংরক্ষিত হয়েছে' },
  'editor.clickToAddField': { en: 'Click to add field', bn: 'ক্ষেত্র যোগ করতে ক্লিক করুন' },
  'editor.assignedTo': { en: 'Assigned to', bn: 'নির্ধারিত' },
  'editor.signee': { en: 'Signee', bn: 'স্বাক্ষরকারী' },
  'editor.couldNotSaveFields': { en: 'Could not save fields', bn: 'ক্ষেত্র সংরক্ষণ করা যায়নি' },
  'editor.changesSaveFailed': { en: 'Your changes could not be saved. Please try again.', bn: 'আপনার পরিবর্তন সংরক্ষণ করা যায়নি। আবার চেষ্টা করুন।' },
  'editor.orphanedFields': { en: 'One or more fields belong to a signer who is no longer on this document. Remove or reassign those fields before sending.', bn: 'এক বা একাধিক ক্ষেত্র এমন স্বাক্ষরকারীর, যিনি আর এই ডকুমেন্টে নেই। পাঠানোর আগে ক্ষেত্রগুলো মুছুন বা পুনরায় নির্ধারণ করুন।' },
  'editor.invalidCcPrefix': { en: 'Check these CC addresses', bn: 'এই CC ঠিকানাগুলো পরীক্ষা করুন' },
  'editor.invitationSent': { en: 'signer invitation sent.', bn: 'টি স্বাক্ষরকারীর আমন্ত্রণ পাঠানো হয়েছে।' },
  'editor.invitationsSent': { en: 'signer invitations sent.', bn: 'টি স্বাক্ষরকারীর আমন্ত্রণ পাঠানো হয়েছে।' },
  'editor.emailFailed': { en: 'email could not be delivered.', bn: 'টি ইমেইল পৌঁছায়নি।' },
  'editor.emailsFailed': { en: 'emails could not be delivered.', bn: 'টি ইমেইল পৌঁছায়নি।' },
  'editor.couldNotSendDocument': { en: 'Could not send document', bn: 'ডকুমেন্ট পাঠানো যায়নি' },
  'editor.documentSendFailed': { en: 'The document could not be sent. Please try again.', bn: 'ডকুমেন্ট পাঠানো যায়নি। আবার চেষ্টা করুন।' },
  'editor.removeSignerFailed': { en: 'The signer could not be removed. Please try again.', bn: 'স্বাক্ষরকারীকে সরানো যায়নি। আবার চেষ্টা করুন।' },
  'editor.noSigners': { en: 'No signers', bn: 'কোনো স্বাক্ষরকারী নেই' },
  'editor.unassigned': { en: 'Unassigned', bn: 'নির্ধারিত নয়' },
  'editor.collapsePanel': { en: 'Collapse field panel', bn: 'ক্ষেত্র প্যানেল বন্ধ করুন' },
  'editor.expandPanel': { en: 'Expand field panel', bn: 'ক্ষেত্র প্যানেল খুলুন' },
  'editor.confirm': { en: 'OK', bn: 'ঠিক আছে' },
  'editor.scrollSignersUp': { en: 'Scroll signer list up', bn: 'স্বাক্ষরকারীর তালিকা উপরে নিন' },
  'editor.scrollSignersDown': { en: 'Scroll signer list down', bn: 'স্বাক্ষরকারীর তালিকা নিচে নিন' },
  'editor.editNamedSigner': { en: 'Edit {name}', bn: '{name} সম্পাদনা করুন' },
  'editor.removeNamedSigner': { en: 'Remove {name}', bn: '{name} মুছুন' },
  'editor.fieldAssignedTo': { en: '{field} field assigned to {name}', bn: '{name}-কে নির্ধারিত {field} ক্ষেত্র' },
  'editor.removeFieldFor': { en: 'Remove {field} field for {name}', bn: '{name}-এর {field} ক্ষেত্র মুছুন' },
  'editor.fieldKeyboardHint': {
    en: 'Use arrow keys to move. Hold Shift and use arrow keys to resize. Hold Alt for smaller adjustments.',
    bn: 'সরাতে অ্যারো কী ব্যবহার করুন। আকার বদলাতে Shift চেপে অ্যারো কী ব্যবহার করুন। আরও ছোট পরিবর্তনের জন্য Alt চেপে রাখুন।',
  },
  'editor.closeFieldSettings': { en: 'Close field settings', bn: 'ক্ষেত্রের সেটিংস বন্ধ করুন' },
  'editor.assignFieldTo': { en: 'Assign field to {name}', bn: '{name}-কে ক্ষেত্রটি নির্ধারণ করুন' },
  'editor.firstNamePlaceholder': { en: 'John', bn: 'রহিম' },
  'editor.lastNamePlaceholder': { en: 'Doe', bn: 'আহমেদ' },
  'editor.signerEmailPlaceholder': { en: 'signer@example.com', bn: 'signer@example.com' },
  'editor.ccPlaceholder': { en: 'e.g. manager@company.com, legal@company.com', bn: 'যেমন: manager@company.com, legal@company.com' },
  'editor.messagePlaceholder': { en: 'Add a message for the signers', bn: 'স্বাক্ষরকারীদের জন্য একটি বার্তা লিখুন' },

  // ─── Signee / Invite Signing Page ───
  'signee.loadingDoc': { en: 'Loading document...', bn: 'ডকুমেন্ট লোড হচ্ছে...' },
  'signee.docNotFound': { en: 'Document Not Found', bn: 'ডকুমেন্ট পাওয়া যায়নি' },
  'signee.docNotFoundDesc': {
    en: "The document you're looking for was not found. It may have been deleted or the link is invalid.",
    bn: 'আপনি যে ডকুমেন্টটি খুঁজছেন তা পাওয়া যায়নি। এটি মুছে ফেলা হয়ে থাকতে পারে অথবা লিঙ্কটি অবৈধ।',
  },
  'signee.signingComplete': { en: 'Signing Complete!', bn: 'স্বাক্ষর সম্পন্ন!' },
  'signee.yourPartComplete': { en: 'Your Signature Is Complete', bn: 'আপনার স্বাক্ষর সম্পন্ন হয়েছে' },
  'signee.thankYou': { en: 'Thank you,', bn: 'ধন্যবাদ,' },
  'signee.allFieldsSigned': {
    en: 'All your fields have been signed successfully.',
    bn: 'আপনার সকল ক্ষেত্র সফলভাবে স্বাক্ষরিত হয়েছে।',
  },
  'signee.waitingForOthers': {
    en: 'Your work is saved. We will send the completed document after every participant has signed.',
    bn: 'আপনার কাজ সংরক্ষিত হয়েছে। সকল অংশগ্রহণকারী স্বাক্ষর করার পর আমরা সম্পূর্ণ ডকুমেন্ট পাঠাব।',
  },
  'signee.consentTitle': { en: 'Electronic signature consent', bn: 'ইলেকট্রনিক স্বাক্ষরের সম্মতি' },
  'signee.consentDescription': {
    en: 'I agree to use electronic records and signatures for this document.',
    bn: 'আমি এই ডকুমেন্টের জন্য ইলেকট্রনিক রেকর্ড ও স্বাক্ষর ব্যবহার করতে সম্মত।',
  },
  'signee.savingConsent': { en: 'Saving your consent...', bn: 'আপনার সম্মতি সংরক্ষণ করা হচ্ছে...' },
  'signee.consentRequired': {
    en: 'Confirm electronic signature consent before completing any fields.',
    bn: 'কোনো ক্ষেত্র পূরণ করার আগে ইলেকট্রনিক স্বাক্ষরের সম্মতি নিশ্চিত করুন।',
  },
  'signee.consentSaveFailed': {
    en: 'Your consent could not be saved. Check your connection and try again.',
    bn: 'আপনার সম্মতি সংরক্ষণ করা যায়নি। সংযোগ পরীক্ষা করে আবার চেষ্টা করুন।',
  },
  'signee.deliveryNeedsRetry': {
    en: 'The document is complete, but the final PDF or completion emails still need to be delivered.',
    bn: 'ডকুমেন্ট সম্পূর্ণ হয়েছে, তবে চূড়ান্ত PDF বা সম্পন্ন হওয়ার ইমেইল এখনও পাঠানো বাকি।',
  },
  'signee.retryDelivery': { en: 'Retry final delivery', bn: 'চূড়ান্ত ডেলিভারি আবার চেষ্টা করুন' },
  'signee.retryingDelivery': { en: 'Retrying delivery...', bn: 'ডেলিভারি আবার চেষ্টা করা হচ্ছে...' },
  'signee.downloadSigned': { en: 'Download Signed Document', bn: 'স্বাক্ষরিত ডকুমেন্ট ডাউনলোড করুন' },
  'signee.viewSigned': { en: 'View Signed Document', bn: 'স্বাক্ষরিত ডকুমেন্ট দেখুন' },
  'signee.downloadIncludesAudit': {
    en: 'Download includes signatures and audit trail certificate',
    bn: 'ডাউনলোডে স্বাক্ষর এবং অডিট ট্রেইল সার্টিফিকেট অন্তর্ভুক্ত',
  },
  'signee.generatingPdf': { en: 'Generating PDF...', bn: 'PDF তৈরি হচ্ছে...' },
  'signee.downloadPdf': { en: 'Download PDF', bn: 'PDF ডাউনলোড করুন' },
  'signee.close': { en: 'Close', bn: 'বন্ধ করুন' },
  'signee.signingAs': { en: 'Signing as', bn: 'স্বাক্ষর করছেন' },
  'signee.yourSignature': { en: 'Your Signature', bn: 'আপনার স্বাক্ষর' },
  'signee.changeSignature': { en: 'Change Signature', bn: 'স্বাক্ষর পরিবর্তন করুন' },
  'signee.createSignature': { en: 'Create Signature', bn: 'স্বাক্ষর তৈরি করুন' },
  'signee.yourInitials': { en: 'Your Initials', bn: 'আপনার ইনিশিয়াল' },
  'signee.changeInitials': { en: 'Change Initials', bn: 'ইনিশিয়াল পরিবর্তন করুন' },
  'signee.addInitials': { en: 'Add Initials', bn: 'ইনিশিয়াল যোগ করুন' },
  'signee.yourFields': { en: 'Your Fields', bn: 'আপনার ক্ষেত্র' },
  'signee.signed': { en: 'signed', bn: 'স্বাক্ষরিত' },
  'signee.places': { en: 'places', bn: 'জায়গা' },
  'signee.allInitialsFilled': { en: 'All initials fields filled', bn: 'সকল ইনিশিয়াল ক্ষেত্র পূরণ হয়েছে' },
  'signee.allSignaturesFilled': { en: 'All signature fields filled', bn: 'সকল স্বাক্ষর ক্ষেত্র পূরণ হয়েছে' },
  'signee.applyToAll': { en: 'Apply to All Initials', bn: 'সকল ইনিশিয়াল প্রয়োগ করুন' },
  'signee.prev': { en: 'Prev', bn: 'আগের' },
  'signee.next': { en: 'Next', bn: 'পরের' },
  'signee.finishSigning': { en: 'Finish Signing', bn: 'স্বাক্ষর সম্পন্ন করুন' },
  'signee.submitting': { en: 'Submitting...', bn: 'জমা দেওয়া হচ্ছে...' },
  'signee.helpTitle': { en: 'How to Sign', bn: 'কিভাবে সাইন করবেন' },
  'signee.help1': {
    en: '1. Create your signature by clicking "Create Signature"',
    bn: '১. "স্বাক্ষর তৈরি করুন" ক্লিক করে আপনার স্বাক্ষর তৈরি করুন',
  },
  'signee.help2': {
    en: '2. Click on each highlighted field on the document to sign',
    bn: '২. সাইন করতে ডকুমেন্টের প্রতিটি হাইলাইট করা ক্ষেত্রে ক্লিক করুন',
  },
  'signee.help3': {
    en: '3. Use "Next" / "Prev" buttons to navigate between fields',
    bn: '৩. ক্ষেত্রগুলোর মধ্যে নেভিগেট করতে "পরের" / "আগের" বাটন ব্যবহার করুন',
  },
  'signee.help4': {
    en: '4. Your part completes automatically after every assigned field is filled',
    bn: '৪. নির্ধারিত সব ক্ষেত্র পূরণ হলে আপনার অংশ স্বয়ংক্রিয়ভাবে সম্পন্ন হবে',
  },
  'signee.help5': {
    en: '5. The final copy becomes available after every participant has signed',
    bn: '৫. সকল অংশগ্রহণকারী স্বাক্ষর করার পর চূড়ান্ত কপি পাওয়া যাবে',
  },
  'signee.tabUpload': { en: 'Upload', bn: 'আপলোড' },
  'signee.tabDraw': { en: 'Draw', bn: 'আঁকুন' },
  'signee.tabType': { en: 'Type', bn: 'টাইপ' },
  'signee.saveSignature': { en: 'Save Signature', bn: 'স্বাক্ষর সংরক্ষণ' },
  'signee.applyToAllSignatures': { en: 'Apply to All Signatures', bn: 'সকল স্বাক্ষরে প্রয়োগ করুন' },
  'signee.applyToAllInitials': { en: 'Apply to All Initials', bn: 'সকল ইনিশিয়াল প্রয়োগ করুন' },
  'signee.createYourSignature': { en: 'Create Your Signature', bn: 'আপনার স্বাক্ষর তৈরি করুন' },
  'signee.addYourInitials': { en: 'Add Your Initials', bn: 'আপনার ইনিশিয়াল যোগ করুন' },
  'signee.drawInitialsHint': { en: 'Draw your initials below. You can apply to individual fields or all at once.', bn: 'নিচে আপনার ইনিশিয়াল আঁকুন। আপনি পৃথক ক্ষেত্রে বা একসাথে সবগুলিতে প্রয়োগ করতে পারেন।' },
  'signee.drawSignature': { en: 'Draw your signature', bn: 'আপনার স্বাক্ষর আঁকুন' },
  'signee.clearSignature': { en: 'Clear drawn signature', bn: 'আঁকা স্বাক্ষর মুছুন' },
  'signee.clear': { en: 'Clear', bn: 'মুছুন' },
  'signee.drawAbove': { en: 'Draw your signature above', bn: 'উপরে আপনার স্বাক্ষর আঁকুন' },
  'signee.typeFullName': { en: 'Type your full name', bn: 'আপনার পুরো নাম লিখুন' },
  'signee.uploadSignatureImage': { en: 'Click to upload a signature image', bn: 'স্বাক্ষরের ছবি আপলোড করতে ক্লিক করুন' },
  'signee.signatureImageFormats': { en: 'PNG, JPG, or WebP up to 2 MB', bn: 'PNG, JPG বা WebP, সর্বোচ্চ ২ MB' },
  'signee.transparentImageHint': { en: 'A transparent background gives the cleanest result.', bn: 'স্বচ্ছ ব্যাকগ্রাউন্ডে ফলাফল সবচেয়ে পরিষ্কার হবে।' },
  'signee.signatureMethod': { en: 'Signature method', bn: 'স্বাক্ষরের পদ্ধতি' },
  'signee.uploadedSignature': { en: 'Uploaded signature preview', bn: 'আপলোড করা স্বাক্ষরের প্রিভিউ' },
  'signee.preparingSignatureImage': { en: 'Preparing signature image...', bn: 'স্বাক্ষরের ছবি প্রস্তুত হচ্ছে...' },
  'signee.signatureImagePrepareFailed': { en: 'The signature image could not be prepared. Try a smaller image.', bn: 'স্বাক্ষরের ছবি প্রস্তুত করা যায়নি। ছোট ছবি দিয়ে আবার চেষ্টা করুন।' },
  'signee.signatureImageEmpty': { en: 'The selected image is empty.', bn: 'নির্বাচিত ছবিটি খালি।' },
  'signee.signatureImageTooLarge': { en: 'The signature image must be 2 MB or smaller.', bn: 'স্বাক্ষরের ছবি ২ MB বা তার কম হতে হবে।' },
  'signee.signatureImageTypeInvalid': { en: 'Use a PNG, JPG, or WebP image.', bn: 'PNG, JPG অথবা WebP ছবি ব্যবহার করুন।' },
  'signee.typeHere': { en: 'Type here...', bn: 'এখানে লিখুন...' },
  'signee.fieldSaveFailed': {
    en: 'This field could not be saved. Your document was refreshed, so you can try again.',
    bn: 'এই ক্ষেত্রটি সংরক্ষণ করা যায়নি। ডকুমেন্টটি রিফ্রেশ করা হয়েছে, এখন আবার চেষ্টা করুন।',
  },
  'signee.completionConfirmFailed': {
    en: 'Your fields were saved, but completion could not be confirmed. Check your connection and try again.',
    bn: 'আপনার ক্ষেত্রগুলো সংরক্ষিত হয়েছে, কিন্তু সম্পন্ন হওয়া নিশ্চিত করা যায়নি। সংযোগ পরীক্ষা করে আবার চেষ্টা করুন।',
  },
  'signee.finalizeFailed': {
    en: 'Everyone has signed, but the document could not be finalized. Please try again.',
    bn: 'সকলেই স্বাক্ষর করেছেন, কিন্তু ডকুমেন্টটি চূড়ান্ত করা যায়নি। আবার চেষ্টা করুন।',
  },
  'signee.signedDocumentGenerateFailed': {
    en: 'The signed document could not be generated. Please try again.',
    bn: 'স্বাক্ষরিত ডকুমেন্ট তৈরি করা যায়নি। আবার চেষ্টা করুন।',
  },
  'signee.signedPdfGenerateFailed': {
    en: 'The signed PDF could not be generated. Please try again.',
    bn: 'স্বাক্ষরিত PDF তৈরি করা যায়নি। আবার চেষ্টা করুন।',
  },
  'signee.openAuditTrail': { en: 'Open audit trail', bn: 'অডিট ইতিহাস খুলুন' },
  'signee.previousUnsignedField': { en: 'Previous unsigned field', bn: 'আগের অসম্পূর্ণ ক্ষেত্র' },
  'signee.nextUnsignedField': { en: 'Next unsigned field', bn: 'পরের অসম্পূর্ণ ক্ষেত্র' },
  'signee.collapsePanel': { en: 'Collapse signing panel', bn: 'স্বাক্ষর প্যানেল বন্ধ করুন' },
  'signee.expandPanel': { en: 'Expand signing panel', bn: 'স্বাক্ষর প্যানেল খুলুন' },
  'signee.signingProgress': { en: 'Signing progress', bn: 'স্বাক্ষরের অগ্রগতি' },
  'signee.signingDate': { en: 'Signing date', bn: 'স্বাক্ষরের তারিখ' },
  'signee.fieldText': { en: 'Field text', bn: 'ক্ষেত্রের লেখা' },
  'signee.signedValue': { en: 'Signed field value', bn: 'স্বাক্ষরিত ক্ষেত্রের মান' },
  'signee.signaturePreview': { en: 'Signature preview', bn: 'স্বাক্ষরের প্রিভিউ' },
  'signee.applyToThis': { en: 'Apply to this', bn: 'এখানে প্রয়োগ করুন' },
  'signee.applyToEveryField': { en: 'Apply to all', bn: 'সব ক্ষেত্রে প্রয়োগ করুন' },
  'signee.activateField': { en: 'Activate to complete this field.', bn: 'এই ক্ষেত্রটি পূরণ করতে সক্রিয় করুন।' },
  'signee.tapToAddDate': { en: 'Tap to add date', bn: 'তারিখ যোগ করতে ট্যাপ করুন' },
  'signee.tapToEnterText': { en: 'Tap to enter text', bn: 'লেখা যোগ করতে ট্যাপ করুন' },
  'signee.tapToSign': { en: 'Tap to sign', bn: 'স্বাক্ষর করতে ট্যাপ করুন' },
  'signee.tapAnyField': { en: 'Tap any field on the PDF to fill it', bn: 'পূরণ করতে PDF-এ যেকোনো ক্ষেত্রে ট্যাপ করুন' },
  'signee.allYourFieldsSigned': { en: 'All your fields are signed!', bn: 'আপনার সব ক্ষেত্র স্বাক্ষরিত হয়েছে!' },
  'signee.saveInitials': { en: 'Save Initials', bn: 'ইনিশিয়াল সংরক্ষণ করুন' },
  'signee.applyToAllCount': { en: 'Apply to All ({count})', bn: 'সব ক্ষেত্রে প্রয়োগ করুন ({count})' },

  // ─── Shared document viewer ───
  'viewer.page': { en: 'page', bn: 'পৃষ্ঠা' },
  'viewer.pages': { en: 'pages', bn: 'পৃষ্ঠা' },
  'viewer.zoomOut': { en: 'Zoom out', bn: 'ছোট করুন' },
  'viewer.zoomIn': { en: 'Zoom in', bn: 'বড় করুন' },
  'viewer.pdfLoadFailed': { en: 'The PDF could not be loaded. Check your connection and try again.', bn: 'PDF লোড করা যায়নি। সংযোগ পরীক্ষা করে আবার চেষ্টা করুন।' },
  'viewer.loadingPdf': { en: 'Loading PDF...', bn: 'PDF লোড হচ্ছে...' },
  'viewer.tryAgain': { en: 'Try again', bn: 'আবার চেষ্টা করুন' },
  'viewer.pdfPage': { en: 'PDF page', bn: 'PDF পৃষ্ঠা' },
  'viewer.placeCenterHint': { en: 'Press Enter to place the selected field in the center.', bn: 'নির্বাচিত ক্ষেত্রটি মাঝখানে রাখতে Enter চাপুন।' },
  'viewer.signingProgress': { en: 'Document signing progress', bn: 'ডকুমেন্ট স্বাক্ষরের অগ্রগতি' },
  'viewer.hideDetails': { en: 'Hide details', bn: 'বিস্তারিত লুকান' },
  'viewer.showDetails': { en: 'Show document details', bn: 'ডকুমেন্টের বিস্তারিত দেখান' },
  'viewer.finalCopyPending': { en: 'Final signed copy is being prepared', bn: 'চূড়ান্ত স্বাক্ষরিত কপি প্রস্তুত হচ্ছে' },
  'viewer.finalCopyPendingDesc': {
    en: 'Everyone has signed, but the final PDF is not ready yet. Please try this link again shortly.',
    bn: 'সবাই স্বাক্ষর করেছেন, তবে চূড়ান্ত PDF এখনো প্রস্তুত নয়। কিছুক্ষণ পর এই লিংকটি আবার চেষ্টা করুন।',
  },

  // ─── Audit trail ───
  'audit.title': { en: 'Audit trail', bn: 'অডিট ইতিহাস' },
  'audit.trail': { en: 'Event', bn: 'ঘটনা' },
  'audit.user': { en: 'User', bn: 'ব্যবহারকারী' },
  'audit.timeLocation': { en: 'Time and location', bn: 'সময় ও অবস্থান' },
  'audit.loading': { en: 'Loading audit history', bn: 'অডিট ইতিহাস লোড হচ্ছে' },
  'audit.noActivity': { en: 'No activity recorded yet', bn: 'এখনো কোনো কার্যক্রম রেকর্ড হয়নি' },
  'audit.documentCreated': { en: 'Document created', bn: 'ডকুমেন্ট তৈরি হয়েছে' },
  'audit.documentSent': { en: 'Document sent', bn: 'ডকুমেন্ট পাঠানো হয়েছে' },
  'audit.documentViewed': { en: 'Document viewed', bn: 'ডকুমেন্ট দেখা হয়েছে' },
  'audit.documentSigned': { en: 'Document signed', bn: 'ডকুমেন্ট স্বাক্ষরিত হয়েছে' },
  'audit.fieldSigned': { en: 'Field signed', bn: 'ক্ষেত্র স্বাক্ষরিত হয়েছে' },
  'audit.allFieldsSigned': { en: 'All fields completed', bn: 'সব ক্ষেত্র সম্পন্ন হয়েছে' },
  'audit.signatureApplied': { en: 'Signature applied', bn: 'স্বাক্ষর যোগ হয়েছে' },
  'audit.initialsAdded': { en: 'Initials added', bn: 'ইনিশিয়াল যোগ হয়েছে' },
  'audit.dateFilled': { en: 'Date filled', bn: 'তারিখ পূরণ হয়েছে' },
  'audit.checkboxChecked': { en: 'Checkbox checked', bn: 'চেকবক্স নির্বাচন হয়েছে' },
  'audit.textEntered': { en: 'Text entered', bn: 'টেক্সট যোগ হয়েছে' },
  'audit.documentCompleted': { en: 'Document completed', bn: 'ডকুমেন্ট সম্পন্ন হয়েছে' },
  'audit.sentForSigning': { en: 'Sent for signing', bn: 'স্বাক্ষরের জন্য পাঠানো হয়েছে' },
  'audit.reminderSent': { en: 'Reminder sent', bn: 'রিমাইন্ডার পাঠানো হয়েছে' },
  'audit.consentGiven': { en: 'Electronic signature consent given', bn: 'ইলেকট্রনিক স্বাক্ষরের সম্মতি দেওয়া হয়েছে' },
  'audit.completionEmailsSent': { en: 'Completion emails sent', bn: 'সম্পন্ন হওয়ার ইমেইল পাঠানো হয়েছে' },
}

export const useLanguageStore = create<LanguageState>((set, get) => {
  const saved = (typeof window !== 'undefined' ? localStorage.getItem('somadhan-lang') : null) as Language | null
  const initialLanguage = saved === 'bn' ? 'bn' : 'en'
  if (typeof document !== 'undefined') document.documentElement.lang = initialLanguage

  return {
    lang: initialLanguage,
    setLang: (lang) => {
      localStorage.setItem('somadhan-lang', lang)
      document.documentElement.lang = lang
      set({ lang })
    },
    toggle: () => {
      const next = get().lang === 'en' ? 'bn' : 'en'
      localStorage.setItem('somadhan-lang', next)
      document.documentElement.lang = next
      set({ lang: next })
    },
    t: (key: string) => {
      const entry = translations[key]
      if (!entry) return key
      return entry[get().lang] || entry.en || key
    },
  }
})
