import { create } from 'zustand'
import { readLocalPreference, writeLocalPreference } from '@/lib/browserStorage'

type Language = 'en' | 'bn'

interface LanguageState {
  lang: Language
  setLang: (lang: Language) => void
  toggle: () => void
  t: (key: string) => string
}

const translations: Record<string, Record<Language, string>> = {
  // ─── Navbar ───
  'nav.signIn': { en: 'Sign In', bn: 'সাইন ইন' },
  'nav.getStarted': { en: 'Get Started', bn: 'শুরু করুন' },
  'nav.documents': { en: 'Documents', bn: 'ডকুমেন্টস' },
  'nav.lightMode': { en: 'Light mode', bn: 'লাইট মোড' },
  'common.closeDialog': { en: 'Close dialog', bn: 'ডায়ালগ বন্ধ করুন' },
  'common.dialog': { en: 'Dialog', bn: 'ডায়ালগ' },
  'common.closeConfirmation': { en: 'Close confirmation', bn: 'নিশ্চিতকরণ বন্ধ করুন' },
  'common.confirmation': { en: 'Confirmation', bn: 'নিশ্চিতকরণ' },
  'common.confirmActionFailed': {
    en: 'The action could not be completed. Check your connection and try again.',
    bn: 'কাজটি সম্পন্ন করা যায়নি। সংযোগ পরীক্ষা করে আবার চেষ্টা করুন।',
  },
  'common.ok': { en: 'OK', bn: 'ঠিক আছে' },
  'common.cancel': { en: 'Cancel', bn: 'বাতিল' },
  'common.skipToContent': { en: 'Skip to main content', bn: 'মূল কনটেন্টে যান' },
  'common.loadingPage': { en: 'Loading page...', bn: 'পৃষ্ঠা লোড হচ্ছে...' },
  'common.loadingDocument': { en: 'Loading document...', bn: 'ডকুমেন্ট লোড হচ্ছে...' },
  'common.homeLabel': { en: 'Somadhan Sign home', bn: 'Somadhan Sign হোম' },
  'common.switchToBangla': { en: 'বাংলা, switch to Bangla', bn: 'বাংলা, বাংলায় পরিবর্তন করুন' },
  'common.switchToEnglish': { en: 'EN, switch to English', bn: 'EN, ইংরেজিতে পরিবর্তন করুন' },
  'common.openMenu': { en: 'Open menu', bn: 'মেনু খুলুন' },
  'common.closeMenu': { en: 'Close menu', bn: 'মেনু বন্ধ করুন' },
  'common.primaryNavigation': { en: 'Primary navigation', bn: 'প্রধান নেভিগেশন' },
  'common.mobileNavigation': { en: 'Mobile navigation', bn: 'মোবাইল নেভিগেশন' },
  'errorBoundary.title': { en: 'Something went wrong', bn: 'কিছু সমস্যা হয়েছে' },
  'errorBoundary.description': { en: 'Your work may still be saved. Reload the page to reconnect and continue.', bn: 'আপনার কাজ সংরক্ষিত থাকতে পারে। আবার সংযোগ করে চালিয়ে যেতে পৃষ্ঠাটি রিলোড করুন।' },
  'errorBoundary.reload': { en: 'Reload page', bn: 'পৃষ্ঠা রিলোড করুন' },
  'notFound.title': { en: 'This page could not be found', bn: 'এই পৃষ্ঠাটি পাওয়া যায়নি' },
  'notFound.description': { en: 'The link may be incorrect or the page may have moved.', bn: 'লিঙ্কটি ভুল হতে পারে অথবা পৃষ্ঠাটি সরানো হয়েছে।' },
  'notFound.returnHome': { en: 'Return home', bn: 'হোমে ফিরুন' },
  'verify.checkingEyebrow': { en: 'DOCUMENT VERIFICATION', bn: 'ডকুমেন্ট যাচাই' },
  'verify.checkingTitle': { en: 'Checking this record', bn: 'রেকর্ডটি যাচাই করা হচ্ছে' },
  'verify.checkingBody': {
    en: 'We are checking the Somadhan Sign completion record.',
    bn: 'Somadhan Sign-এ সংরক্ষিত সমাপ্তির রেকর্ডটি পরীক্ষা করা হচ্ছে।',
  },
  'verify.recordEyebrow': { en: 'RECORD FOUND', bn: 'রেকর্ড পাওয়া গেছে' },
  'verify.recordTitle': { en: 'Completion record is active', bn: 'সমাপ্তির রেকর্ডটি সক্রিয় আছে' },
  'verify.recordBody': {
    en: 'Somadhan Sign has an active completion record for this certificate. Keep the reference below if you need support.',
    bn: 'এই সনদের জন্য Somadhan Sign-এ একটি সক্রিয় সমাপ্তির রেকর্ড রয়েছে। প্রয়োজনে সহায়তা পেতে নিচের রেফারেন্সটি সংরক্ষণ করুন।',
  },
  'verify.notFoundEyebrow': { en: 'NOT VERIFIED', bn: 'যাচাই করা যায়নি' },
  'verify.notFoundTitle': { en: 'We could not verify this QR', bn: 'এই QR যাচাই করা যায়নি' },
  'verify.notFoundBody': {
    en: 'This link does not match a Somadhan Sign verification record. Scan the QR again from the completed PDF.',
    bn: 'এই লিঙ্কটি Somadhan Sign-এর কোনো যাচাইকরণ রেকর্ডের সঙ্গে মেলেনি। সম্পন্ন PDF থেকে QR আবার স্ক্যান করুন।',
  },
  'verify.revokedEyebrow': { en: 'VERIFICATION WITHDRAWN', bn: 'যাচাই প্রত্যাহার করা হয়েছে' },
  'verify.revokedTitle': { en: 'This record is no longer verified', bn: 'এই রেকর্ডটি আর যাচাইকৃত নয়' },
  'verify.revokedBody': {
    en: 'Somadhan Sign no longer confirms this record. Contact the person or organization that provided the document.',
    bn: 'Somadhan Sign এই রেকর্ডটি আর নিশ্চিত করছে না। যিনি বা যে প্রতিষ্ঠান ডকুমেন্টটি দিয়েছে, তাদের সঙ্গে যোগাযোগ করুন।',
  },
  'verify.unavailableEyebrow': { en: 'CHECK INCOMPLETE', bn: 'যাচাই সম্পন্ন হয়নি' },
  'verify.unavailableTitle': { en: 'Verification is temporarily unavailable', bn: 'এই মুহূর্তে যাচাই করা যাচ্ছে না' },
  'verify.unavailableBody': {
    en: 'We could not reach the verification service. This record has not been marked invalid.',
    bn: 'যাচাই সেবার সঙ্গে সংযোগ করা যায়নি। তবে রেকর্ডটিকে অবৈধ হিসেবে চিহ্নিত করা হয়নি।',
  },
  'verify.offlineBody': {
    en: 'You appear to be offline. Reconnect and try again.',
    bn: 'আপনি সম্ভবত অফলাইনে আছেন। ইন্টারনেটে সংযুক্ত হয়ে আবার চেষ্টা করুন।',
  },
  'verify.recordStatus': { en: 'Record status', bn: 'রেকর্ডের অবস্থা' },
  'verify.active': { en: 'Active', bn: 'সক্রিয়' },
  'verify.completed': { en: 'Completed', bn: 'সম্পন্ন' },
  'verify.reference': { en: 'Reference', bn: 'রেফারেন্স' },
  'verify.copyReference': { en: 'Copy verification reference', bn: 'যাচাইকরণ রেফারেন্স কপি করুন' },
  'verify.guidanceTitle': { en: 'What this check means', bn: 'এই যাচাই থেকে যা জানা যায়' },
  'verify.guidanceBody': {
    en: 'The QR connects this certificate to a Somadhan Sign completion record. Open the audit trail to review the recorded signing events.',
    bn: 'QR কোডটি এই সনদকে Somadhan Sign-এ সংরক্ষিত সমাপ্তির রেকর্ডের সঙ্গে যুক্ত করে। স্বাক্ষরের ঘটনাগুলো দেখতে অডিট ইতিহাস খুলুন।',
  },
  'verify.privacyNote': {
    en: 'For privacy, this page does not show the document title or signer details.',
    bn: 'গোপনীয়তার জন্য এই পৃষ্ঠায় ডকুমেন্টের নাম বা স্বাক্ষরকারীদের তথ্য দেখানো হয় না।',
  },
  'verify.viewAuditTrail': { en: 'View audit trail', bn: 'অডিট ইতিহাস দেখুন' },
  'verify.hideAuditTrail': { en: 'Hide audit trail', bn: 'অডিট ইতিহাস লুকান' },
  'verify.auditTrailTitle': { en: 'Recorded signing events', bn: 'সংরক্ষিত স্বাক্ষরের ঘটনাবলি' },
  'verify.auditTrailEmpty': { en: 'No signing events are available for this record.', bn: 'এই রেকর্ডের জন্য স্বাক্ষরের কোনো ঘটনা পাওয়া যায়নি।' },
  'verify.tryAgain': { en: 'Try again', bn: 'আবার চেষ্টা করুন' },
  'verify.disclaimer': {
    en: 'This page confirms a Somadhan Sign completion record. It does not independently determine legal validity or a signer’s identity.',
    bn: 'এই পৃষ্ঠা Somadhan Sign-এ সমাপ্তির রেকর্ড থাকার বিষয়টি নিশ্চিত করে। এটি নিজে থেকে ডকুমেন্টের আইনি বৈধতা বা স্বাক্ষরকারীর পরিচয় প্রমাণ করে না।',
  },
  'verify.goHome': { en: 'Go to Somadhan Sign', bn: 'Somadhan Sign-এ যান' },
  'nav.darkMode': { en: 'Dark mode', bn: 'ডার্ক মোড' },
  'nav.signOut': { en: 'Sign out', bn: 'সাইন আউট' },
  'nav.signingOut': { en: 'Signing out...', bn: 'সাইন আউট হচ্ছে...' },
  'nav.signOutFailed': { en: 'Could not sign out. Check your connection and try again.', bn: 'সাইন আউট করা যায়নি। সংযোগ পরীক্ষা করে আবার চেষ্টা করুন।' },

  // ─── Landing Page ───
  'landing.heroTitle1': { en: 'Sign documents with', bn: 'ডকুমেন্ট সাইন করুন' },
  'landing.heroTitle2': { 
    en: 'SomadhanSign', 
    bn: 'Somadhan Sign দিয়ে'
  },
  'landing.heroDesc': {
    en: 'Upload documents, define signature fields, invite multiple signers, and get everything signed in one beautiful platform.',
    bn: 'ডকুমেন্ট আপলোড করুন, স্বাক্ষরের জায়গা ঠিক করুন, একাধিক স্বাক্ষরকারীকে আমন্ত্রণ জানান এবং পুরো প্রক্রিয়াটি এক জায়গা থেকে সম্পন্ন করুন।',
  },
  'landing.navProduct': { en: 'Product', bn: 'প্রোডাক্ট' },
  'landing.navCapabilities': { en: 'Capabilities', bn: 'সুবিধাসমূহ' },
  'landing.navSecurity': { en: 'Security', bn: 'নিরাপত্তা' },
  'landing.heroKicker': { en: 'Documents, ready for action', bn: 'ডকুমেন্ট এখন আরও সহজ' },
  'landing.heroNewTitle': { en: 'Digital signature', bn: 'ডিজিটাল স্বাক্ষর' },
  'landing.heroNewAccent': { en: 'simplified', bn: 'এখন আরও সহজ' },
  'landing.heroNewDesc': {
    en: 'Prepare, send, sign, and track important PDFs in a workspace that keeps every person and every action clear.',
    bn: 'গুরুত্বপূর্ণ PDF প্রস্তুত করা থেকে পাঠানো, স্বাক্ষর ও অগ্রগতি দেখা পর্যন্ত পুরো কাজটি করুন একটি সহজ ও গোছানো ওয়ার্কস্পেসে।',
  },
  'landing.watchProduct': { en: 'See how it works', bn: 'কীভাবে কাজ করে দেখুন' },
  'landing.noInstall': { en: 'No installation', bn: 'ইনস্টল করার দরকার নেই' },
  'landing.productEyebrow': { en: 'The signing flow', bn: 'স্বাক্ষর প্রক্রিয়া' },
  'landing.productTitle': { en: 'One document. Every step in view.', bn: 'একটি ডকুমেন্ট, প্রতিটি ধাপ চোখের সামনে' },
  'landing.productDesc': {
    en: 'Move from upload to completed signature without losing context. Explore the flow to see exactly what happens next.',
    bn: 'আপলোড থেকে স্বাক্ষর সম্পন্ন হওয়া পর্যন্ত প্রতিটি ধাপ একসঙ্গে দেখুন। এরপর কী করতে হবে, তা সব সময় পরিষ্কার থাকবে।',
  },
  'landing.demoUpload': { en: 'Upload', bn: 'আপলোড' },
  'landing.demoUploadCaption': { en: 'Bring in your PDF', bn: 'আপনার PDF যোগ করুন' },
  'landing.demoPrepare': { en: 'Prepare', bn: 'প্রস্তুত করুন' },
  'landing.demoPrepareCaption': { en: 'Place the right fields', bn: 'সঠিক ক্ষেত্র বসান' },
  'landing.demoInvite': { en: 'Invite', bn: 'আমন্ত্রণ' },
  'landing.demoInviteCaption': { en: 'Assign every signer', bn: 'প্রত্যেকের কাজ ঠিক করুন' },
  'landing.demoComplete': { en: 'Complete', bn: 'সম্পূর্ণ' },
  'landing.demoCompleteCaption': { en: 'Finish with a clear record', bn: 'নির্ভরযোগ্য রেকর্ডসহ শেষ করুন' },
  'landing.pause': { en: 'Pause', bn: 'বিরতি দিন' },
  'landing.resume': { en: 'Resume', bn: 'আবার চালু করুন' },
  'landing.pauseDemo': { en: 'Pause automatic roadmap changes', bn: 'রোডম্যাপের স্বয়ংক্রিয় পরিবর্তন থামান' },
  'landing.resumeDemo': { en: 'Resume automatic roadmap changes', bn: 'রোডম্যাপের স্বয়ংক্রিয় পরিবর্তন আবার চালু করুন' },
  'landing.demoDocument': { en: 'Agreement.pdf', bn: 'চুক্তিপত্র.pdf' },
  'landing.workspacePreview': { en: 'Somadhan Sign document workspace preview', bn: 'Somadhan Sign ডকুমেন্ট ওয়ার্কস্পেসের প্রিভিউ' },
  'landing.demoReady': { en: 'Ready to prepare for signing', bn: 'স্বাক্ষরের জন্য প্রস্তুত' },
  'landing.demoReadyStatus': { en: 'Ready', bn: 'প্রস্তুত' },
  'landing.demoDraft': { en: 'Draft', bn: 'খসড়া' },
  'landing.demoFields': { en: 'Fields', bn: 'ক্ষেত্র' },
  'landing.demoSignHere': { en: 'Sign here', bn: 'এখানে স্বাক্ষর করুন' },
  'landing.demoSignersReady': { en: 'Signers ready', bn: 'স্বাক্ষরকারীরা প্রস্তুত' },
  'landing.demoFieldsAssigned': { en: 'Each field is assigned', bn: 'প্রতিটি ক্ষেত্র নির্ধারিত' },
  'landing.demoInviteTitle': { en: 'Invite signers', bn: 'স্বাক্ষরকারী আমন্ত্রণ করুন' },
  'landing.demoInviteDesc': { en: 'Every signer gets their own fields', bn: 'প্রত্যেকে নিজের নির্ধারিত ক্ষেত্র পাবেন' },
  'landing.demoInvitationsReady': { en: 'Invitations ready', bn: 'আমন্ত্রণ প্রস্তুত' },
  'landing.demoSignedComplete': { en: 'Signed and complete', bn: 'স্বাক্ষরিত ও সম্পূর্ণ' },
  'landing.demoAuditTrail': { en: 'Audit trail', bn: 'অডিট ইতিহাস' },
  'landing.demoVerified': { en: 'Verified', bn: 'যাচাইকৃত' },
  'landing.demoDocumentCreated': { en: 'Document created', bn: 'ডকুমেন্ট তৈরি হয়েছে' },
  'landing.demoInvitationsDelivered': { en: 'Invitations delivered', bn: 'আমন্ত্রণ পৌঁছেছে' },
  'landing.demoAllSigned': { en: 'All signatures completed', bn: 'সব স্বাক্ষর সম্পন্ন' },
  'landing.capabilityEyebrow': { en: 'Built for real documents', bn: 'বাস্তব ডকুমেন্টের জন্য' },
  'landing.capabilityTitle': { en: 'Less friction at every handoff.', bn: 'প্রতিটি ধাপে কম ঝামেলা।' },
  'landing.capabilityDesc': {
    en: 'Somadhan Sign keeps preparation simple for senders and makes the final signing experience obvious for everyone else.',
    bn: 'Somadhan Sign প্রেরকের জন্য ডকুমেন্ট প্রস্তুত করা সহজ করে এবং স্বাক্ষরকারীদের প্রতিটি ধাপে স্পষ্ট নির্দেশনা দেয়।',
  },
  'landing.securityEyebrow': { en: 'Clarity and control', bn: 'স্বচ্ছতা ও নিয়ন্ত্রণ' },
  'landing.securityTitle': { en: 'Know what happened to every document.', bn: 'প্রতিটি ডকুমেন্টের সব খবর রাখুন' },
  'landing.securityDesc': {
    en: 'Follow document activity, signer progress, and final completion from one place with a detailed audit history.',
    bn: 'ডকুমেন্টের কার্যক্রম, স্বাক্ষরকারীদের অগ্রগতি এবং কাজ সম্পন্ন হওয়ার তথ্য বিস্তারিত অডিট ইতিহাসে এক জায়গায় দেখুন।',
  },
  'landing.securityItem1': { en: 'Signer-specific fields', bn: 'স্বাক্ষরকারীভিত্তিক ক্ষেত্র' },
  'landing.securityItem2': { en: 'Status tracking', bn: 'স্ট্যাটাস ট্র্যাকিং' },
  'landing.securityItem3': { en: 'Detailed audit history', bn: 'বিস্তারিত অডিট ইতিহাস' },
  'landing.securityItem4': { en: 'Completed PDF export', bn: 'সম্পূর্ণ PDF এক্সপোর্ট' },
  'landing.ctaEyebrow': { en: 'Your next document', bn: 'আপনার পরবর্তী ডকুমেন্ট' },
  'landing.ctaNewTitle': { en: 'Your next signature starts here.', bn: 'আপনার পরবর্তী স্বাক্ষর শুরু হোক এখানেই।' },
  'landing.ctaNewDesc': {
    en: 'Prepare your document, invite every signer, and keep the whole process clear from the first send.',
    bn: 'ডকুমেন্ট প্রস্তুত করুন, স্বাক্ষরকারীদের আমন্ত্রণ জানান এবং শুরু থেকে শেষ পর্যন্ত পুরো প্রক্রিয়াটি সহজে অনুসরণ করুন।',
  },
  'landing.getStartedFree': { en: 'Start Free', bn: 'বিনামূল্যে শুরু করুন' },
  'landing.startNow': { en: 'Start Now', bn: 'এখনই শুরু করুন' },
  'landing.signIn': { en: 'Sign In', bn: 'সাইন ইন' },
  'landing.howItWorks': { en: 'How it works', bn: 'কীভাবে কাজ করে' },
  'landing.howItWorksDesc': {
    en: 'Get documents signed in four simple steps',
    bn: 'মাত্র চারটি সহজ ধাপে ডকুমেন্ট স্বাক্ষর সম্পন্ন করুন',
  },
  'landing.step1Title': { en: 'Upload your PDF', bn: 'আপনার PDF আপলোড করুন' },
  'landing.step1Desc': { en: 'Drag and drop or browse to upload', bn: 'টেনে আনুন বা ব্রাউজ করে আপলোড করুন' },
  'landing.step2Title': { en: 'Define signature fields', bn: 'স্বাক্ষরের জায়গা ঠিক করুন' },
  'landing.step2Desc': { en: 'Click on the PDF to place fields', bn: 'ক্ষেত্র রাখতে PDF-এ ক্লিক করুন' },
  'landing.step3Title': { en: 'Assign signers', bn: 'স্বাক্ষরকারী যোগ করুন' },
  'landing.step3Desc': { en: 'Add emails and assign fields to each signer', bn: 'ইমেইল যোগ করে প্রত্যেকের জন্য প্রয়োজনীয় ক্ষেত্র ঠিক করুন' },
  'landing.step4Title': { en: 'Send for signing', bn: 'স্বাক্ষরের জন্য পাঠান' },
  'landing.step4Desc': { en: 'Signers receive an email with a link', bn: 'স্বাক্ষরকারীরা লিঙ্ক সহ একটি ইমেইল পাবেন' },
  'landing.everything': { en: 'Everything you need', bn: 'আপনার যা দরকার সবকিছু' },
  'landing.everythingDesc': {
    en: 'Powerful features to handle any document signing workflow',
    bn: 'যেকোনো ডকুমেন্ট স্বাক্ষর প্রক্রিয়া সহজে পরিচালনার জন্য দরকারি সব সুবিধা',
  },
  'landing.feat.upload': { en: 'Upload Documents', bn: 'ডকুমেন্ট আপলোড' },
  'landing.feat.uploadDesc': {
    en: 'Upload any PDF document and prepare it for signing in seconds.',
    bn: 'যেকোনো PDF ডকুমেন্ট আপলোড করুন এবং কয়েক সেকেন্ডে স্বাক্ষরের জন্য প্রস্তুত করুন।',
  },
  'landing.feat.fields': { en: 'Place Signature Fields', bn: 'স্বাক্ষর ক্ষেত্র রাখুন' },
  'landing.feat.fieldsDesc': {
    en: 'Drag and drop signature fields anywhere on the document. Assign each field to a specific signer.',
    bn: 'ডকুমেন্টের যেকোনো জায়গায় স্বাক্ষরের ক্ষেত্র বসান এবং প্রতিটি ক্ষেত্র নির্দিষ্ট স্বাক্ষরকারীকে দিন।',
  },
  'landing.feat.multi': { en: 'Multi-Party Signing', bn: 'মাল্টি-পার্টি স্বাক্ষর' },
  'landing.feat.multiDesc': {
    en: 'Invite multiple signers. Each signer sees only their assigned fields with guided navigation.',
    bn: 'একাধিক স্বাক্ষরকারী আমন্ত্রণ করুন। প্রতিটি স্বাক্ষরকারী শুধু তাদের নির্ধারিত ক্ষেত্র দেখবেন।',
  },
  'landing.feat.track': { en: 'Send & Track', bn: 'পাঠান ও ট্র্যাক করুন' },
  'landing.feat.trackDesc': {
    en: 'Send documents for signing and track progress from your dashboard.',
    bn: 'স্বাক্ষরের জন্য ডকুমেন্ট পাঠান এবং ড্যাশবোর্ড থেকে অগ্রগতি ট্র্যাক করুন।',
  },
  'landing.feat.secure': { en: 'Controlled Access', bn: 'নিয়ন্ত্রিত অ্যাক্সেস' },
  'landing.feat.secureDesc': {
    en: 'Unique signer links and a detailed activity history make document access and events easier to track.',
    bn: 'প্রত্যেক স্বাক্ষরকারীর আলাদা লিঙ্ক ও বিস্তারিত কার্যক্রমের ইতিহাস থাকায় ডকুমেন্টে প্রবেশ এবং প্রতিটি ঘটনা অনুসরণ করা সহজ হয়।',
  },
  'landing.feat.anywhere': { en: 'Sign Anywhere', bn: 'যেকোনো জায়গা থেকে স্বাক্ষর করুন' },
  'landing.feat.anywhereDesc': {
    en: 'Draw, type, or upload your signature. Sign all fields at once or one by one.',
    bn: 'স্বাক্ষর আঁকুন, টাইপ করুন অথবা ছবি আপলোড করুন। সব ক্ষেত্রে একসঙ্গে কিংবা একটি করে স্বাক্ষর দিন।',
  },
  'landing.ctaTitle': { en: 'Ready to get started?', bn: 'শুরু করতে প্রস্তুত?' },
  'landing.ctaDesc': {
    en: 'Create an account and start preparing your first document.',
    bn: 'অ্যাকাউন্ট তৈরি করুন এবং আপনার প্রথম ডকুমেন্ট প্রস্তুত করুন।',
  },
  'landing.createFreeAccount': { en: 'Start Now', bn: 'এখনই শুরু করুন' },
  'landing.freeToStart': { en: 'Free to start', bn: 'বিনামূল্যে শুরু' },
  'landing.noCreditCard': { en: 'No credit card', bn: 'ক্রেডিট কার্ড লাগবে না' },
  'landing.unlimitedDocs': { en: 'Unlimited documents', bn: 'সীমাহীন ডকুমেন্ট' },
  'landing.footer': { en: 'Somadhan. All rights reserved.', bn: 'সমাধান। সর্বস্বত্ব সংরক্ষিত।' },

  // ─── Login Page ───
  'login.welcomeBack': { en: 'Welcome back', bn: 'স্বাগতম' },
  'login.signInToContinue': { en: 'Sign in to your account to continue', bn: 'এগিয়ে যেতে আপনার অ্যাকাউন্টে সাইন ইন করুন' },
  'login.continueWithGoogle': { en: 'Continue with Google', bn: 'গুগল দিয়ে চালিয়ে যান' },
  'login.orContinueWithEmail': { en: 'OR CONTINUE WITH EMAIL', bn: 'অথবা ইমেইল দিয়ে চালিয়ে যান' },
  'login.email': { en: 'Email', bn: 'ইমেইল' },
  'login.password': { en: 'Password', bn: 'পাসওয়ার্ড' },
  'login.fullName': { en: 'Full Name', bn: 'পুরো নাম' },
  'login.signIn': { en: 'Sign In', bn: 'সাইন ইন' },
  'login.signUp': { en: 'Sign Up', bn: 'সাইন আপ' },
  'login.forgotPassword': { en: 'Forgot password?', bn: 'পাসওয়ার্ড ভুলে গেছেন?' },
  'login.noAccount': { en: "Don't have an account?", bn: 'অ্যাকাউন্ট নেই?' },
  'login.hasAccount': { en: 'Already have an account?', bn: 'ইতিমধ্যে অ্যাকাউন্ট আছে?' },
  'login.signUpLink': { en: 'Sign up', bn: 'সাইন আপ করুন' },
  'login.signInLink': { en: 'Sign in', bn: 'সাইন ইন করুন' },
  'login.createAccount': { en: 'Create account', bn: 'অ্যাকাউন্ট তৈরি করুন' },
  'login.createAccountDesc': { en: 'Enter your details to get started', bn: 'শুরু করতে আপনার তথ্য দিন' },
  'login.resetPassword': { en: 'Reset your password', bn: 'পাসওয়ার্ড রিসেট করুন' },
  'login.resetPasswordDesc': {
    en: "Enter your email and we'll send you a password reset link",
    bn: 'আপনার ইমেইল দিন। আমরা সেখানে পাসওয়ার্ড রিসেট করার লিঙ্ক পাঠাব।',
  },
  'login.sendResetLink': { en: 'Send Reset Link', bn: 'রিসেট লিঙ্ক পাঠান' },
  'login.alreadyRegistered': {
    en: 'This email is already registered. Sign in with your password, or use "Forgot password?" to reset it. If you signed up with Google, choose "Continue with Google" instead.',
    bn: 'এই ইমেইল দিয়ে ইতিমধ্যে একটি অ্যাকাউন্ট আছে। পাসওয়ার্ড দিয়ে সাইন ইন করুন অথবা "পাসওয়ার্ড ভুলে গেছেন?" থেকে নতুন পাসওয়ার্ড নিন। Google দিয়ে অ্যাকাউন্ট খুলে থাকলে "Google দিয়ে চালিয়ে যান" বেছে নিন।',
  },
  'login.backToSignIn': { en: 'Back to sign in', bn: 'সাইন ইন-এ ফিরে যান' },
  'login.verifyEmail': { en: 'Verify your email', bn: 'আপনার ইমেইল যাচাই করুন' },
  'login.verifyEmailDesc': { en: 'Enter the 6-digit code sent to', bn: 'এই ঠিকানায় পাঠানো ৬ সংখ্যার কোডটি লিখুন' },
  'login.verifyCode': { en: 'Verify Code', bn: 'কোড যাচাই করুন' },
  'login.resendCode': { en: 'Resend Code', bn: 'কোড পুনরায় পাঠান' },
  'login.signingIn': { en: 'Signing in...', bn: 'সাইন ইন হচ্ছে...' },
  'login.creatingAccount': { en: 'Creating account...', bn: 'অ্যাকাউন্ট তৈরি হচ্ছে...' },
  'login.sendingResetLink': { en: 'Sending reset link...', bn: 'রিসেট লিঙ্ক পাঠানো হচ্ছে...' },
  'login.verifyingCode': { en: 'Verifying code...', bn: 'কোড যাচাই করা হচ্ছে...' },
  'login.verificationSent': { en: 'If this email can be registered, a 6-digit verification code is on its way.', bn: 'এই ইমেইল দিয়ে নিবন্ধন করা সম্ভব হলে ৬ সংখ্যার যাচাইকরণ কোড পাঠানো হবে।' },
  'login.resetLinkSent': { en: 'Password reset link has been sent to your email. Please check your inbox.', bn: 'পাসওয়ার্ড রিসেট লিঙ্ক আপনার ইমেইলে পাঠানো হয়েছে। ইনবক্স দেখুন।' },
  'login.genericError': { en: 'Something went wrong. Please try again.', bn: 'কিছু সমস্যা হয়েছে। আবার চেষ্টা করুন।' },
  'login.googleStartFailed': { en: 'Google sign-in could not be started. Please try again.', bn: 'Google সাইন ইন শুরু করা যায়নি। আবার চেষ্টা করুন।' },
  'login.tooManyAttempts': { en: 'Too many attempts. Please try again in {minutes} minutes.', bn: 'অনেকবার চেষ্টা করা হয়েছে। {minutes} মিনিট পর আবার চেষ্টা করুন।' },
  'login.otpBlocked': { en: 'Too many verification-code attempts. Try again in 1 hour.', bn: 'যাচাইকরণ কোড অনেকবার দেওয়া হয়েছে। ১ ঘণ্টা পর আবার চেষ্টা করুন।' },
  'login.newOtpSent': { en: 'New verification code sent. Check your email.', bn: 'নতুন যাচাইকরণ কোড পাঠানো হয়েছে। ইমেইল দেখুন।' },
  'login.resendFailed': { en: 'The verification code could not be resent. Please try again.', bn: 'যাচাইকরণ কোড আবার পাঠানো যায়নি। আবার চেষ্টা করুন।' },
  'login.otpLabel': { en: '6-digit verification code', bn: '৬ সংখ্যার যাচাইকরণ কোড' },
  'login.didNotReceiveCode': { en: "Didn't receive the code?", bn: 'কোড পাননি?' },
  'login.resendOtp': { en: 'Resend code', bn: 'কোড আবার পাঠান' },
  'login.resendOtpCountdown': { en: 'Resend code ({seconds}s)', bn: 'কোড আবার পাঠান ({seconds} সেকেন্ড)' },
  'login.backToSignup': { en: 'Back to sign up', bn: 'সাইন আপে ফিরে যান' },
  'login.namePlaceholder': { en: 'John Doe', bn: 'রহিম আহমেদ' },
  'login.showPassword': { en: 'Show password', bn: 'পাসওয়ার্ড দেখান' },
  'login.hidePassword': { en: 'Hide password', bn: 'পাসওয়ার্ড লুকান' },
  'login.passwordHint': { en: 'Use at least 8 characters.', bn: 'কমপক্ষে ৮ অক্ষর ব্যবহার করুন।' },
  'login.passwordPlaceholder': { en: 'Enter your password', bn: 'আপনার পাসওয়ার্ড লিখুন' },
  'login.brandingTitle': { en: 'Sign documents with', bn: 'ডকুমেন্ট সাইন করুন' },
  'login.brandingDesc': {
    en: 'Upload, define signature fields, invite signers, and get documents signed in one place.',
    bn: 'ডকুমেন্ট আপলোড করুন, স্বাক্ষরের জায়গা ঠিক করুন, স্বাক্ষরকারীদের আমন্ত্রণ জানান এবং পুরো কাজটি এক জায়গা থেকে সম্পন্ন করুন।',
  },
  'login.brandingEyebrow': { en: 'A clearer way to sign', bn: 'স্বাক্ষরের আরও সহজ উপায়' },
  'login.brandingNewTitle1': { en: 'Your document.', bn: 'আপনার ডকুমেন্ট' },
  'login.brandingNewTitle2': { en: 'Ready for everyone.', bn: 'সবার স্বাক্ষরের জন্য প্রস্তুত' },
  'login.statDocuments': { en: 'Documents', bn: 'ডকুমেন্ট' },
  'login.statUsers': { en: 'Users', bn: 'ব্যবহারকারী' },
  'login.statUptime': { en: 'Uptime', bn: 'আপটাইম' },
  'login.copyright': { en: 'Somadhan. All rights reserved.', bn: 'সমাধান। সর্বস্বত্ব সংরক্ষিত।' },
  'login.accountVerified': { en: 'Account Verified!', bn: 'অ্যাকাউন্ট যাচাই হয়েছে!' },
  'login.accountVerifiedDesc': {
    en: 'Your email has been confirmed. You can now use SomadhanSign.',
    bn: 'আপনার ইমেইল নিশ্চিত হয়েছে। আপনি এখন সমাধান সাইন ব্যবহার করতে পারেন।',
  },
  'login.letsGo': { en: "OK, Let's Go!", bn: 'চলুন শুরু করি!' },

  // ─── Password Reset ───
  'reset.setNewPassword': { en: 'Set New Password', bn: 'নতুন পাসওয়ার্ড সেট করুন' },
  'reset.enterNewPassword': { en: 'Enter your new password below', bn: 'নিচে আপনার নতুন পাসওয়ার্ড দিন' },
  'reset.validatingLink': { en: 'Validating your secure reset link...', bn: 'পাসওয়ার্ড রিসেট করার নিরাপদ লিঙ্কটি যাচাই করা হচ্ছে...' },
  'reset.newPassword': { en: 'New Password', bn: 'নতুন পাসওয়ার্ড' },
  'reset.confirmPassword': { en: 'Confirm Password', bn: 'পাসওয়ার্ড নিশ্চিত করুন' },
  'reset.updatePassword': { en: 'Update Password', bn: 'পাসওয়ার্ড আপডেট করুন' },
  'reset.updatingPassword': { en: 'Updating password...', bn: 'পাসওয়ার্ড আপডেট হচ্ছে...' },
  'reset.passwordUpdated': { en: 'Password Updated!', bn: 'পাসওয়ার্ড আপডেট হয়েছে!' },
  'reset.passwordUpdatedDesc': {
    en: 'Your password has been successfully reset. You can now sign in with your new password.',
    bn: 'আপনার পাসওয়ার্ড সফলভাবে রিসেট হয়েছে। এখন আপনি নতুন পাসওয়ার্ড দিয়ে সাইন ইন করতে পারেন।',
  },
  'reset.goToLogin': { en: 'Go to Login', bn: 'লগইন পেজে যান' },
  'reset.backToLogin': { en: 'Back to Login', bn: 'লগইনে ফিরে যান' },
  'reset.passwordTooShort': { en: 'Password must be at least 8 characters.', bn: 'পাসওয়ার্ড কমপক্ষে ৮ অক্ষরের হতে হবে।' },
  'reset.passwordsDoNotMatch': { en: 'Passwords do not match.', bn: 'পাসওয়ার্ড মিলছে না।' },
  'reset.linkExpired': {
    en: 'This password reset link has expired or is invalid. Please request a new one.',
    bn: 'পাসওয়ার্ড রিসেট করার এই লিঙ্কটির মেয়াদ শেষ হয়েছে অথবা এটি সঠিক নয়। নতুন একটি লিঙ্কের অনুরোধ করুন।',
  },
  'reset.errorOccurred': { en: 'An error occurred. Please try again.', bn: 'একটি ত্রুটি ঘটেছে। আবার চেষ্টা করুন।' },
  'reset.failedToUpdate': { en: 'Failed to update password', bn: 'পাসওয়ার্ড আপডেট করতে ব্যর্থ' },

  // ─── Dashboard ───
  'dashboard.myDocuments': { en: 'My Documents', bn: 'আমার ডকুমেন্ট' },
  'dashboard.newDocument': { en: 'New Document', bn: 'নতুন ডকুমেন্ট' },
  'dashboard.searchDocs': { en: 'Search documents...', bn: 'ডকুমেন্ট খুঁজুন...' },
  'dashboard.noDocuments': { en: 'No documents yet', bn: 'এখনো কোনো ডকুমেন্ট নেই' },
  'dashboard.noMatches': { en: 'No matching documents', bn: 'আপনার খোঁজের সঙ্গে কোনো ডকুমেন্ট মেলেনি' },
  'dashboard.adjustFilters': { en: 'Try another search or status filter.', bn: 'অন্য কিছু খুঁজুন বা স্ট্যাটাস ফিল্টার পরিবর্তন করুন।' },
  'dashboard.clearFilters': { en: 'Clear filters', bn: 'ফিল্টার মুছুন' },
  'dashboard.backToDashboard': { en: 'Back to dashboard', bn: 'ড্যাশবোর্ডে ফিরে যান' },
  'dashboard.allSignersDone': { en: 'All signers done', bn: 'সবাই স্বাক্ষর করেছেন' },
  'dashboard.signers': { en: 'Signers', bn: 'স্বাক্ষরকারী' },
  'dashboard.signed': { en: 'Signed', bn: 'স্বাক্ষরিত' },
  'dashboard.viewed': { en: 'Viewed', bn: 'দেখেছেন' },
  'dashboard.viewAuditTrail': { en: 'View audit trail', bn: 'অডিট ইতিহাস দেখুন' },
  'dashboard.preparing': { en: 'Preparing...', bn: 'প্রস্তুত হচ্ছে...' },
  'dashboard.downloading': { en: 'Downloading...', bn: 'ডাউনলোড হচ্ছে...' },
  'dashboard.downloadSignedPdf': { en: 'Download signed PDF', bn: 'স্বাক্ষরিত PDF ডাউনলোড করুন' },
  'dashboard.downloadOriginalPdf': { en: 'Download original PDF', bn: 'মূল PDF ডাউনলোড করুন' },
  'dashboard.documentUnavailable': { en: 'The document could not be found or is no longer available.', bn: 'ডকুমেন্টটি পাওয়া যায়নি বা আর উপলভ্য নেই।' },
  'documentLoad.failedTitle': { en: 'Document could not be loaded', bn: 'ডকুমেন্ট লোড করা যায়নি' },
  'documentLoad.failedDescription': {
    en: 'Check your connection and try again. Your document has not been changed.',
    bn: 'আপনার সংযোগ পরীক্ষা করে আবার চেষ্টা করুন। আপনার ডকুমেন্টে কোনো পরিবর্তন করা হয়নি।',
  },
  'dashboard.signedDownloadFailed': { en: 'The signed PDF could not be prepared. Please try again.', bn: 'স্বাক্ষরিত PDF প্রস্তুত করা যায়নি। আবার চেষ্টা করুন।' },
  'dashboard.originalDownloadFailed': { en: 'The original PDF could not be downloaded. Please try again.', bn: 'মূল PDF ডাউনলোড করা যায়নি। আবার চেষ্টা করুন।' },
  'dashboard.preparingDownload': { en: 'Preparing your download...', bn: 'আপনার ডাউনলোড প্রস্তুত করা হচ্ছে...' },
  'dashboard.downloadStarted': { en: 'Your download has started.', bn: 'আপনার ডাউনলোড শুরু হয়েছে।' },
  'dashboard.uploadFirst': {
    en: 'Upload your first PDF to get started',
    bn: 'শুরু করতে আপনার প্রথম PDF আপলোড করুন',
  },
  'dashboard.uploadPdf': { en: 'Upload PDF', bn: 'PDF আপলোড করুন' },
  'dashboard.draft': { en: 'Draft', bn: 'খসড়া' },
  'dashboard.pending': { en: 'Pending', bn: 'অপেক্ষমাণ' },
  'dashboard.completed': { en: 'Completed', bn: 'সম্পন্ন' },
  'dashboard.cancelled': { en: 'Cancelled', bn: 'বাতিল' },
  'dashboard.delete': { en: 'Delete', bn: 'মুছুন' },
  'dashboard.edit': { en: 'Edit', bn: 'সম্পাদনা' },
  'dashboard.view': { en: 'View', bn: 'দেখুন' },
  'dashboard.sendReminder': { en: 'Send Reminder', bn: 'রিমাইন্ডার পাঠান' },
  'dashboard.cancelSigningRequest': { en: 'Cancel signing request', bn: 'স্বাক্ষরের অনুরোধ বাতিল করুন' },
  'dashboard.cancelRequest': { en: 'Cancel request', bn: 'অনুরোধ বাতিল করুন' },
  'dashboard.cancelSigningConfirm': {
    en: 'Cancel signing for "{title}"? Signers will no longer be able to complete their fields. The document and its activity history will remain available.',
    bn: '"{title}"-এর স্বাক্ষর প্রক্রিয়া বাতিল করবেন? এরপর স্বাক্ষরকারীরা আর তাদের নির্ধারিত ক্ষেত্র পূরণ করতে পারবেন না। ডকুমেন্ট ও কার্যক্রমের ইতিহাস সংরক্ষিত থাকবে।',
  },
  'dashboard.signingRequestCancelled': { en: 'The signing request has been cancelled.', bn: 'স্বাক্ষরের অনুরোধ বাতিল করা হয়েছে।' },
  'dashboard.total': { en: 'Total', bn: 'মোট' },
  'dashboard.drafts': { en: 'Drafts', bn: 'খসড়া' },
  'dashboard.all': { en: 'All', bn: 'সব' },
  'dashboard.download': { en: 'Download', bn: 'ডাউনলোড' },
  'dashboard.auditTrail': { en: 'Audit Trail', bn: 'অডিট ইতিহাস' },
  'dashboard.deleteDocument': { en: 'Delete Document', bn: 'ডকুমেন্ট মুছুন' },
  'dashboard.deleteDraftConfirm': {
    en: 'Delete the draft "{title}"? Its PDF and field setup will be permanently removed.',
    bn: '"{title}" খসড়াটি মুছবেন? এর PDF এবং ক্ষেত্রের সেটআপ স্থায়ীভাবে মুছে যাবে।',
  },
  'dashboard.deleteCompletedConfirm': {
    en: 'Delete the completed document "{title}"? Its signed PDF and complete activity history will be permanently removed.',
    bn: '"{title}" সম্পন্ন ডকুমেন্টটি মুছবেন? এর স্বাক্ষরিত PDF এবং সম্পূর্ণ কার্যক্রমের ইতিহাস স্থায়ীভাবে মুছে যাবে।',
  },
  'dashboard.deleteCancelledConfirm': {
    en: 'Delete the cancelled document "{title}"? Its PDF and activity history will be permanently removed.',
    bn: '"{title}" বাতিল করা ডকুমেন্টটি মুছবেন? এর PDF এবং কার্যক্রমের ইতিহাস স্থায়ীভাবে মুছে যাবে।',
  },
  'dashboard.enterTitle': { en: 'Enter a document title.', bn: 'ডকুমেন্টের শিরোনাম লিখুন।' },
  'dashboard.titleTooLong': { en: 'Use 160 characters or fewer for the document title.', bn: 'ডকুমেন্টের শিরোনাম ১৬০ অক্ষর বা তার কম রাখুন।' },
  'dashboard.loadingDocuments': { en: 'Loading documents...', bn: 'ডকুমেন্ট লোড হচ্ছে...' },
  'dashboard.documentsLoadFailed': { en: 'Your documents could not be loaded', bn: 'আপনার ডকুমেন্টগুলো লোড করা যায়নি' },
  'dashboard.documentsLoadFailedDesc': {
    en: 'Your files have not been removed. Check your connection and try loading them again.',
    bn: 'আপনার ফাইলগুলো মুছে যায়নি। সংযোগ পরীক্ষা করে আবার লোড করার চেষ্টা করুন।',
  },
  'dashboard.uploadFailed': { en: 'The document could not be uploaded. Check your connection and try again.', bn: 'ডকুমেন্ট আপলোড করা যায়নি। সংযোগ পরীক্ষা করে আবার চেষ্টা করুন।' },
  'dashboard.loadingSigners': { en: 'Loading signers...', bn: 'স্বাক্ষরকারীদের লোড করা হচ্ছে...' },
  'dashboard.signersLoadFailed': { en: 'Signer details could not be loaded.', bn: 'স্বাক্ষরকারীদের তথ্য লোড করা যায়নি।' },
  'dashboard.noSigners': { en: 'No signers', bn: 'কোনো স্বাক্ষরকারী নেই' },
  'dashboard.reminderSentTo': { en: 'Reminder sent to', bn: 'রিমাইন্ডার পাঠানো হয়েছে' },
  'dashboard.pendingSigner': { en: 'pending signer', bn: 'জন অপেক্ষমাণ স্বাক্ষরকারীকে' },
  'dashboard.pendingSigners': { en: 'pending signers', bn: 'জন অপেক্ষমাণ স্বাক্ষরকারীকে' },
  'dashboard.failedCount': { en: 'failed', bn: 'টি ব্যর্থ হয়েছে' },
  'dashboard.reminderFailed': { en: 'The reminder could not be sent. Please try again.', bn: 'রিমাইন্ডার পাঠানো যায়নি। আবার চেষ্টা করুন।' },
  'dashboard.noPendingSigners': { en: 'No pending signers to remind.', bn: 'রিমাইন্ডার দেওয়ার মতো অপেক্ষমাণ স্বাক্ষরকারী নেই।' },
  'dashboard.completedPdfFailed': { en: 'The completed PDF could not be generated. Please try again.', bn: 'সম্পন্ন PDF তৈরি করা যায়নি। আবার চেষ্টা করুন।' },
  'dashboard.showingDocuments': { en: 'Showing {start}-{end} of {total} documents', bn: 'মোট {total}টি ডকুমেন্টের মধ্যে {start}-{end} দেখানো হচ্ছে' },
  'dashboard.pageOf': { en: 'Page {page} of {total}', bn: 'পৃষ্ঠা {page}, মোট {total}' },
  'dashboard.previous': { en: 'Previous', bn: 'আগের' },
  'dashboard.next': { en: 'Next', bn: 'পরের' },
  'dashboard.uploadDocument': { en: 'Upload Document', bn: 'ডকুমেন্ট আপলোড করুন' },
  'dashboard.documentTitle': { en: 'Document Title', bn: 'ডকুমেন্টের শিরোনাম' },
  'dashboard.documentTitlePlaceholder': { en: 'e.g. Contract Agreement', bn: 'যেমন: চুক্তিপত্র' },
  'dashboard.pdfFile': { en: 'PDF File', bn: 'PDF ফাইল' },
  'dashboard.clickUploadPdf': { en: 'Click to upload PDF', bn: 'PDF আপলোড করতে ক্লিক করুন' },
  'dashboard.pdfLimit': { en: 'PDF files up to 5 MB', bn: 'সর্বোচ্চ ৫ MB PDF ফাইল' },
  'dashboard.uploadAndContinue': { en: 'Upload and Continue', bn: 'আপলোড করে এগিয়ে যান' },
  'dashboard.uploading': { en: 'Uploading...', bn: 'আপলোড হচ্ছে...' },
  'dashboard.createdOn': { en: 'Created {date}', bn: 'তৈরি হয়েছে {date}' },
  'dashboard.openDocument': { en: 'Open {title}', bn: '{title} খুলুন' },
  'dashboard.showSignersFor': { en: 'Show signers for {title}', bn: '{title} এর স্বাক্ষরকারীদের দেখান' },
  'dashboard.hideSignersFor': { en: 'Hide signers for {title}', bn: '{title} এর স্বাক্ষরকারীদের লুকান' },
  'dashboard.openActionsFor': { en: 'Open actions for {title}', bn: '{title} এর কাজগুলো খুলুন' },
  'dashboard.documentDeleted': { en: 'Document deleted.', bn: 'ডকুমেন্ট মুছে ফেলা হয়েছে।' },
  'dashboard.deleteFailed': { en: 'The document could not be deleted. Please try again.', bn: 'ডকুমেন্ট মুছে ফেলা যায়নি। আবার চেষ্টা করুন।' },
  'dashboard.confirm': { en: 'OK', bn: 'ঠিক আছে' },
  'dashboard.pdfEmpty': { en: 'The selected PDF is empty.', bn: 'নির্বাচিত PDF ফাইলটি খালি।' },
  'dashboard.pdfTooLarge': { en: 'The PDF must be 5 MB or smaller.', bn: 'PDF ফাইলটি ৫ MB বা তার কম হতে হবে।' },
  'dashboard.pdfRequired': { en: 'Please select a PDF file.', bn: 'একটি PDF ফাইল নির্বাচন করুন।' },
  'dashboard.pdfInvalidHeader': { en: 'This file does not contain a valid PDF header.', bn: 'এই ফাইলটিতে বৈধ PDF হেডার নেই।' },
  'dashboard.pdfUnsupported': { en: 'The PDF is damaged, encrypted, or unsupported.', bn: 'PDF ফাইলটি ক্ষতিগ্রস্ত, এনক্রিপ্ট করা, অথবা সমর্থিত নয়।' },
  'dashboard.pdfNoPages': { en: 'The PDF does not contain any pages.', bn: 'PDF ফাইলটিতে কোনো পৃষ্ঠা নেই।' },
  'dashboard.pdfUnsafeContent': {
    en: 'This PDF contains active content or attachments that cannot be signed safely.',
    bn: 'এই PDF-এ সক্রিয় কনটেন্ট বা সংযুক্তি আছে, তাই এটি নিরাপদভাবে স্বাক্ষর করা যাবে না।',
  },

  // ─── Document Editor ───
  'editor.signers': { en: 'Signers', bn: 'স্বাক্ষরকারী' },
  'editor.selectNamedSigner': { en: 'Select signer {name}', bn: 'স্বাক্ষরকারী {name} নির্বাচন করুন' },
  'editor.addSigner': { en: 'Add Signer', bn: 'স্বাক্ষরকারী যোগ করুন' },
  'editor.addAndAnotherSigner': {
    en: 'Add and enter another',
    bn: 'যোগ করে আরেকজনের তথ্য দিন',
  },
  'editor.fields': { en: 'Fields', bn: 'ক্ষেত্র' },
  'editor.selectTool': { en: 'Select and move', bn: 'নির্বাচন ও সরানো' },
  'editor.clearAllFields': { en: 'Clear all fields', bn: 'সব ক্ষেত্র মুছুন' },
  'editor.clearFields': { en: 'Clear fields', bn: 'ক্ষেত্র মুছুন' },
  'editor.clearAllFieldsConfirm': {
    en: 'Remove every field from this document? This action cannot be undone.',
    bn: 'এই ডকুমেন্ট থেকে সব ক্ষেত্র মুছে ফেলবেন? এই কাজটি পূর্বাবস্থায় ফেরানো যাবে না।',
  },
  'editor.cannotClearSignedFields': {
    en: 'Fields that already contain signer responses cannot be cleared.',
    bn: 'যেসব ক্ষেত্রে স্বাক্ষরকারীর উত্তর রয়েছে সেগুলো মুছে ফেলা যাবে না।',
  },
  'editor.fieldOverlapTitle': { en: 'Fields cannot overlap', bn: 'ক্ষেত্র একটির ওপর আরেকটি রাখা যাবে না' },
  'editor.fieldOverlapMessage': {
    en: 'Choose an empty area. Fields must not cover one another.',
    bn: 'একটি খালি জায়গা বেছে নিন। ক্ষেত্রগুলো একে অপরকে ঢেকে রাখতে পারবে না।',
  },
  'editor.signature': { en: 'Signature', bn: 'স্বাক্ষর' },
  'editor.initials': { en: 'Initials', bn: 'ইনিশিয়াল' },
  'editor.date': { en: 'Date', bn: 'তারিখ' },
  'editor.checkbox': { en: 'Checkbox', bn: 'চেকবক্স' },
  'editor.text': { en: 'Text', bn: 'টেক্সট' },
  'editor.saveDraft': { en: 'Save Draft', bn: 'খসড়া সংরক্ষণ' },
  'editor.saving': { en: 'Saving...', bn: 'সংরক্ষণ হচ্ছে...' },
  'editor.saved': { en: 'All changes saved', bn: 'সব পরিবর্তন সংরক্ষিত' },
  'editor.changesPending': { en: 'Changes waiting to save', bn: 'পরিবর্তনগুলো সংরক্ষণের অপেক্ষায় আছে' },
  'editor.autosaveFailed': { en: 'Changes are not saved. Check your connection and try again.', bn: 'পরিবর্তন সংরক্ষিত হয়নি। সংযোগ পরীক্ষা করে আবার চেষ্টা করুন।' },
  'editor.unsavedChanges': { en: 'Save your changes?', bn: 'আপনার পরিবর্তন সংরক্ষণ করবেন?' },
  'editor.unsavedChangesMessage': {
    en: 'Your latest field changes have not finished saving. Save them before leaving this page.',
    bn: 'আপনার সর্বশেষ ক্ষেত্রের পরিবর্তনগুলো এখনও সংরক্ষণ শেষ হয়নি। এই পৃষ্ঠা ছাড়ার আগে সেগুলো সংরক্ষণ করুন।',
  },
  'editor.saveAndLeave': { en: 'Save and leave', bn: 'সংরক্ষণ করে বের হন' },
  'editor.stayHere': { en: 'Stay here', bn: 'এখানেই থাকুন' },
  'editor.sendForSigning': { en: 'Send for Signing', bn: 'স্বাক্ষরের জন্য পাঠান' },
  'editor.locked': { en: 'Document sent. Editing is locked', bn: 'ডকুমেন্ট পাঠানো হয়েছে। এখন আর সম্পাদনা করা যাবে না' },
  'editor.helpTitle': { en: 'Quick Guide', bn: 'দ্রুত নির্দেশিকা' },
  'editor.help1': {
    en: '1. Add signers using the + button above',
    bn: '১. উপরের + বাটন ব্যবহার করে স্বাক্ষরকারী যোগ করুন',
  },
  'editor.help2': {
    en: '2. Select a field type below (Signature, Initials, etc.)',
    bn: '২. নিচে একটি ক্ষেত্রের ধরন নির্বাচন করুন (স্বাক্ষর, ইনিশিয়াল, ইত্যাদি)',    
  },
  'editor.help3': {
    en: '3. Click the PDF wherever that field is needed. The tool stays active for repeated placement',
    bn: '৩. ডকুমেন্টের যেখানে ক্ষেত্রটি দরকার, সেখানে ক্লিক করুন। একই ধরনের আরও ক্ষেত্র বসাতে টুলটি সক্রিয় থাকবে',
  },
  'editor.help4': {
    en: '4. Click a placed field to assign it to a signer',
    bn: '৪. বসানো কোনো ক্ষেত্রে ক্লিক করে সেটি যাঁর জন্য, তাঁকে নির্বাচন করুন',
  },
  'editor.help5': {
    en: '5. Changes save automatically. Send when ready',
    bn: '৫. পরিবর্তন স্বয়ংক্রিয়ভাবে সংরক্ষিত হবে। প্রস্তুত হলে পাঠান',
  },
  'editor.clickFieldHint': {
    en: 'Click a field on the PDF to see its details and change the assigned signer.',
    bn: 'ক্ষেত্রের বিস্তারিত দেখতে এবং নির্ধারিত স্বাক্ষরকারী পরিবর্তন করতে PDF-এ একটি ক্ষেত্রে ক্লিক করুন।',
  },
  'editor.addSignerFirst': { en: 'Please add at least one signer first.', bn: 'অনুগ্রহ করে প্রথমে কমপক্ষে একজন স্বাক্ষরকারী যোগ করুন।' },
  'editor.assignAllFields': { en: 'Please assign every field to a signer before sending.', bn: 'পাঠানোর আগে প্রতিটি ক্ষেত্র কোনো স্বাক্ষরকারীকে দিন।' },
  'editor.addSignerRequired': { en: 'Please add at least one signer.', bn: 'অনুগ্রহ করে কমপক্ষে একজন স্বাক্ষরকারী যোগ করুন।' },
  'editor.addFieldRequired': { en: 'Please add at least one field to the document.', bn: 'অনুগ্রহ করে ডকুমেন্টে কমপক্ষে একটি ক্ষেত্র যোগ করুন।' },
  'editor.signatureFieldRequired': { en: 'Please add at least one signature field for', bn: 'কমপক্ষে একটি স্বাক্ষরের ক্ষেত্র যোগ করুন এই স্বাক্ষরকারীর জন্য:' },
  'editor.everySignerMustHaveSignature': { en: 'Every signer must have a signature field.', bn: 'প্রত্যেক স্বাক্ষরকারীর একটি স্বাক্ষর ক্ষেত্র থাকতে হবে।' },
  'editor.cannotDeleteSigned': { en: 'This field cannot be deleted because a signer has already completed it.', bn: 'ক্ষেত্রটি মুছে ফেলা যাবে না, কারণ একজন স্বাক্ষরকারী ইতিমধ্যে এটি পূরণ করেছেন।' },
  'editor.removeSignerConfirm': { en: 'Remove this signer and all their fields?', bn: 'এই স্বাক্ষরকারী ও তাঁর সব ক্ষেত্র মুছে ফেলবেন?' },
  'editor.removeSigner': { en: 'Remove Signer', bn: 'স্বাক্ষরকারী মুছুন' },
  'editor.failedSaveSigner': { en: 'Failed to save signer. Please try again.', bn: 'স্বাক্ষরকারী সংরক্ষণ করতে ব্যর্থ। আবার চেষ্টা করুন।' },
  'editor.invalidEmail': { en: 'Please enter a valid email address.', bn: 'অনুগ্রহ করে একটি সঠিক ইমেইল ঠিকানা দিন।' },
  'editor.duplicateEmail': { en: 'This email is already included on this document.', bn: 'এই ইমেইলটি ইতিমধ্যে এই ডকুমেন্টে যোগ করা হয়েছে।' },
  'editor.error': { en: 'Error', bn: 'ত্রুটি' },
  'editor.validation': { en: 'Check required', bn: 'তথ্য যাচাই করুন' },
  'editor.addSignerFirstDesc': { en: 'You need to add at least one signer before placing fields on the document.', bn: 'ডকুমেন্টে ক্ষেত্র রাখার আগে আপনাকে কমপক্ষে একজন স্বাক্ষরকারী যোগ করতে হবে।' },
  'editor.editSigner': { en: 'Edit Signer', bn: 'স্বাক্ষরকারী সম্পাদনা করুন' },
  'editor.sendForSigningTitle': { en: 'Send for Signing', bn: 'স্বাক্ষরের জন্য পাঠান' },
  'editor.sendingDocument': { en: 'Sending Document...', bn: 'ডকুমেন্ট পাঠানো হচ্ছে...' },
  'editor.pleaseWait': { en: 'Please wait while we email the signers.', bn: 'স্বাক্ষরকারীদের ইমেইল পাঠানো হচ্ছে। অনুগ্রহ করে অপেক্ষা করুন।' },
  'editor.documentSent': { en: 'Document Sent!', bn: 'ডকুমেন্ট পাঠানো হয়েছে!' },
  'editor.signersWillReceive': { en: 'Signers will receive emails shortly.', bn: 'স্বাক্ষরকারীরা শীঘ্রই ইমেইল পাবেন।' },
  'editor.redirecting': { en: 'Returning to the dashboard in', bn: 'ড্যাশবোর্ডে ফিরে যাচ্ছেন' },
  'editor.close': { en: 'Close', bn: 'বন্ধ করুন' },
  'editor.firstName': { en: 'First Name', bn: 'প্রথম নাম' },
  'editor.lastName': { en: 'Last Name', bn: 'শেষ নাম' },
  'editor.email': { en: 'Email', bn: 'ইমেইল' },
  'editor.cancel': { en: 'Cancel', bn: 'বাতিল' },
  'editor.saveChanges': { en: 'Save Changes', bn: 'পরিবর্তন সংরক্ষণ করুন' },
  'editor.documentName': { en: 'Document Name', bn: 'ডকুমেন্টের নাম' },
  'editor.ccEmail': { en: 'CC: Email a copy (optional)', bn: 'CC: একটি কপি ইমেইল করুন (ঐচ্ছিক)' },
  'editor.messageForSignees': { en: 'Message for signees (optional)', bn: 'স্বাক্ষরকারীদের জন্য বার্তা (ঐচ্ছিক)' },
  'editor.defaultSendMessage': {
    en: 'Please review and sign this document at your earliest convenience. If you have any questions or need clarification, please contact the sender. Thank you.',
    bn: 'অনুগ্রহ করে সুবিধাজনক সময়ে ডকুমেন্টটি পর্যালোচনা করে স্বাক্ষর করুন। কোনো প্রশ্ন বা ব্যাখ্যার প্রয়োজন হলে প্রেরকের সঙ্গে যোগাযোগ করুন। ধন্যবাদ।',
  },
  'editor.sending': { en: 'Sending...', bn: 'পাঠানো হচ্ছে...' },
  'editor.send': { en: 'Send', bn: 'পাঠান' },
  'editor.savedSuccess': { en: 'Document saved successfully', bn: 'ডকুমেন্ট সফলভাবে সংরক্ষিত হয়েছে' },
  'editor.clickToAddField': { en: 'Click to add field', bn: 'ক্ষেত্র যোগ করতে ক্লিক করুন' },
  'editor.assignedTo': { en: 'Assigned to', bn: 'নির্ধারিত' },
  'editor.signee': { en: 'Signee', bn: 'স্বাক্ষরকারী' },
  'editor.couldNotSaveFields': { en: 'Could not save fields', bn: 'ক্ষেত্র সংরক্ষণ করা যায়নি' },
  'editor.changesSaveFailed': { en: 'Your changes could not be saved. Please try again.', bn: 'আপনার পরিবর্তন সংরক্ষণ করা যায়নি। আবার চেষ্টা করুন।' },
  'editor.orphanedFields': { en: 'One or more fields belong to a signer who is no longer on this document. Remove or reassign those fields before sending.', bn: 'এক বা একাধিক ক্ষেত্র এমন স্বাক্ষরকারীর, যিনি আর এই ডকুমেন্টে নেই। পাঠানোর আগে ক্ষেত্রগুলো মুছুন বা পুনরায় নির্ধারণ করুন।' },
  'editor.invalidCcPrefix': { en: 'Check these CC addresses', bn: 'এই CC ঠিকানাগুলো পরীক্ষা করুন' },
  'editor.invitationSent': { en: 'signer invitation sent.', bn: 'টি স্বাক্ষরকারীর আমন্ত্রণ পাঠানো হয়েছে।' },
  'editor.invitationsSent': { en: 'signer invitations sent.', bn: 'টি স্বাক্ষরকারীর আমন্ত্রণ পাঠানো হয়েছে।' },
  'editor.emailFailed': { en: 'email could not be delivered.', bn: 'টি ইমেইল পৌঁছায়নি।' },
  'editor.emailsFailed': { en: 'emails could not be delivered.', bn: 'টি ইমেইল পৌঁছায়নি।' },
  'editor.couldNotSendDocument': { en: 'Could not send document', bn: 'ডকুমেন্ট পাঠানো যায়নি' },
  'editor.documentSendFailed': { en: 'The document could not be sent. Please try again.', bn: 'ডকুমেন্ট পাঠানো যায়নি। আবার চেষ্টা করুন।' },
  'editor.noInvitationsSent': {
    en: 'No invitation emails were delivered. The document remains pending, so you can retry from the dashboard.',
    bn: 'কোনো আমন্ত্রণ ইমেইল পৌঁছায়নি। ডকুমেন্টটি অপেক্ষমাণ আছে, তাই ড্যাশবোর্ড থেকে আবার চেষ্টা করতে পারবেন।',
  },
  'editor.removeSignerFailed': { en: 'The signer could not be removed. Please try again.', bn: 'স্বাক্ষরকারীকে সরানো যায়নি। আবার চেষ্টা করুন।' },
  'editor.noSigners': { en: 'No signers', bn: 'কোনো স্বাক্ষরকারী নেই' },
  'editor.unassigned': { en: 'Unassigned', bn: 'নির্ধারিত নয়' },
  'editor.collapsePanel': { en: 'Collapse field panel', bn: 'ক্ষেত্র প্যানেল বন্ধ করুন' },
  'editor.expandPanel': { en: 'Expand field panel', bn: 'ক্ষেত্র প্যানেল খুলুন' },
  'editor.confirm': { en: 'OK', bn: 'ঠিক আছে' },
  'editor.scrollSignersUp': { en: 'Scroll signer list up', bn: 'স্বাক্ষরকারীর তালিকা উপরে নিন' },
  'editor.scrollSignersDown': { en: 'Scroll signer list down', bn: 'স্বাক্ষরকারীর তালিকা নিচে নিন' },
  'editor.editNamedSigner': { en: 'Edit {name}', bn: '{name} সম্পাদনা করুন' },
  'editor.removeNamedSigner': { en: 'Remove {name}', bn: '{name} মুছুন' },
  'editor.fieldAssignedTo': { en: '{field} field assigned to {name}', bn: '{name}-কে নির্ধারিত {field} ক্ষেত্র' },
  'editor.removeFieldFor': { en: 'Remove {field} field for {name}', bn: '{name}-এর {field} ক্ষেত্র মুছুন' },
  'editor.fieldKeyboardHint': {
    en: 'Use arrow keys to move. Hold Shift and use arrow keys to resize. Hold Alt for smaller adjustments.',
    bn: 'সরাতে অ্যারো কী ব্যবহার করুন। আকার বদলাতে Shift চেপে অ্যারো কী ব্যবহার করুন। আরও ছোট পরিবর্তনের জন্য Alt চেপে রাখুন।',
  },
  'editor.closeFieldSettings': { en: 'Close field settings', bn: 'ক্ষেত্রের সেটিংস বন্ধ করুন' },
  'editor.assignFieldTo': { en: 'Assign field to {name}', bn: 'ক্ষেত্রটি {name}-কে দিন' },
  'editor.firstNamePlaceholder': { en: 'John', bn: 'রহিম' },
  'editor.lastNamePlaceholder': { en: 'Doe', bn: 'আহমেদ' },
  'editor.signerEmailPlaceholder': { en: 'signer@example.com', bn: 'signer@example.com' },
  'editor.ccPlaceholder': { en: 'e.g. manager@company.com, legal@company.com', bn: 'যেমন: manager@company.com, legal@company.com' },
  'editor.messagePlaceholder': { en: 'Add a message for the signers', bn: 'স্বাক্ষরকারীদের জন্য একটি বার্তা লিখুন' },

  // ─── Signee / Invite Signing Page ───
  'signee.loadingDoc': { en: 'Loading document...', bn: 'ডকুমেন্ট লোড হচ্ছে...' },
  'signee.docNotFound': { en: 'Document Not Found', bn: 'ডকুমেন্ট পাওয়া যায়নি' },
  'signee.docNotFoundDesc': {
    en: "The document you're looking for was not found. It may have been deleted or the link is invalid.",
    bn: 'আপনি যে ডকুমেন্টটি খুঁজছেন তা পাওয়া যায়নি। এটি মুছে ফেলা হয়ে থাকতে পারে অথবা লিঙ্কটি অবৈধ।',
  },
  'signee.noFieldsAssigned': {
    en: 'Nothing is assigned to you',
    bn: 'আপনার জন্য কোনো ক্ষেত্র নির্ধারিত নেই',
  },
  'signee.noFieldsAssignedDesc': {
    en: 'This invitation does not contain any fields for your email address. Contact the sender and ask for a corrected signing request.',
    bn: 'এই আমন্ত্রণে আপনার জন্য কোনো ক্ষেত্র নির্ধারণ করা হয়নি। প্রেরকের সঙ্গে যোগাযোগ করে সংশোধিত স্বাক্ষরের অনুরোধ পাঠাতে বলুন।',
  },
  'signee.signingComplete': { en: 'Signing Complete!', bn: 'স্বাক্ষর সম্পন্ন!' },
  'signee.yourPartComplete': { en: 'Your part is complete', bn: 'আপনার অংশের কাজ সম্পন্ন হয়েছে' },
  'signee.thankYou': { en: 'Thank you,', bn: 'ধন্যবাদ,' },
  'signee.allFieldsSigned': {
    en: 'All your fields have been signed successfully.',
    bn: 'আপনার জন্য নির্ধারিত সব ক্ষেত্র সফলভাবে পূরণ হয়েছে।',
  },
  'signee.waitingForOthers': {
    en: 'Your work is saved. We will send the completed document after every participant has signed.',
    bn: 'আপনার কাজ সংরক্ষিত হয়েছে। সবাই স্বাক্ষর করার পর সম্পন্ন ডকুমেন্টটি আমরা পাঠিয়ে দেব।',
  },
  'signee.consentTitle': { en: 'Electronic signature consent', bn: 'ইলেকট্রনিক স্বাক্ষরের সম্মতি' },
  'signee.consentDescription': {
    en: 'I agree to use electronic records and signatures for this document.',
    bn: 'আমি এই ডকুমেন্টের জন্য ইলেকট্রনিক রেকর্ড ও স্বাক্ষর ব্যবহার করতে সম্মত।',
  },
  'signee.savingConsent': { en: 'Saving your consent...', bn: 'আপনার সম্মতি সংরক্ষণ করা হচ্ছে...' },
  'signee.consentRequired': {
    en: 'Confirm electronic signature consent before completing any fields.',
    bn: 'কোনো ক্ষেত্র পূরণ করার আগে ইলেকট্রনিক স্বাক্ষরের সম্মতি নিশ্চিত করুন।',
  },
  'signee.consentSaveFailed': {
    en: 'Your consent could not be saved. Check your connection and try again.',
    bn: 'আপনার সম্মতি সংরক্ষণ করা যায়নি। সংযোগ পরীক্ষা করে আবার চেষ্টা করুন।',
  },
  'signee.deliveryNeedsRetry': {
    en: 'The document is complete, but the final PDF or completion emails still need to be delivered.',
    bn: 'ডকুমেন্ট সম্পূর্ণ হয়েছে, তবে চূড়ান্ত PDF বা সম্পন্ন হওয়ার ইমেইল এখনও পাঠানো বাকি।',
  },
  'signee.requestCancelled': { en: 'Signing request cancelled', bn: 'স্বাক্ষরের অনুরোধ বাতিল করা হয়েছে' },
  'signee.requestCancelledDesc': {
    en: 'The sender cancelled this signing request. No changes can be submitted from this link.',
    bn: 'প্রেরক স্বাক্ষরের এই অনুরোধটি বাতিল করেছেন। এই লিঙ্ক থেকে আর কোনো পরিবর্তন জমা দেওয়া যাবে না।',
  },
  'signee.retryDelivery': { en: 'Retry final delivery', bn: 'চূড়ান্ত কপি আবার পাঠানোর চেষ্টা করুন' },
  'signee.retryingDelivery': { en: 'Retrying delivery...', bn: 'চূড়ান্ত কপি আবার পাঠানোর চেষ্টা চলছে...' },
  'signee.downloadSigned': { en: 'Download Signed Document', bn: 'স্বাক্ষরিত ডকুমেন্ট ডাউনলোড করুন' },
  'signee.viewSigned': { en: 'View Signed Document', bn: 'স্বাক্ষরিত ডকুমেন্ট দেখুন' },
  'signee.downloadIncludesAudit': {
    en: 'Download includes signatures and audit trail certificate',
    bn: 'ডাউনলোডে স্বাক্ষরসহ অডিট ইতিহাসের সনদ থাকবে',
  },
  'signee.generatingPdf': { en: 'Generating PDF...', bn: 'PDF তৈরি হচ্ছে...' },
  'signee.downloadPdf': { en: 'Download PDF', bn: 'PDF ডাউনলোড করুন' },
  'signee.close': { en: 'Close', bn: 'বন্ধ করুন' },
  'signee.signingAs': { en: 'Signing as', bn: 'স্বাক্ষর করছেন' },
  'signee.yourSignature': { en: 'Your Signature', bn: 'আপনার স্বাক্ষর' },
  'signee.changeSignature': { en: 'Change Signature', bn: 'স্বাক্ষর পরিবর্তন করুন' },
  'signee.createSignature': { en: 'Create Signature', bn: 'স্বাক্ষর তৈরি করুন' },
  'signee.yourInitials': { en: 'Your Initials', bn: 'আপনার ইনিশিয়াল' },
  'signee.changeInitials': { en: 'Change Initials', bn: 'ইনিশিয়াল পরিবর্তন করুন' },
  'signee.addInitials': { en: 'Add Initials', bn: 'ইনিশিয়াল যোগ করুন' },
  'signee.yourFields': { en: 'Your Fields', bn: 'আপনার ক্ষেত্র' },
  'signee.signed': { en: 'signed', bn: 'স্বাক্ষরিত' },
  'signee.places': { en: 'places', bn: 'জায়গা' },
  'signee.allInitialsFilled': { en: 'All initials fields filled', bn: 'ইনিশিয়ালের সব ক্ষেত্র পূরণ হয়েছে' },
  'signee.allSignaturesFilled': { en: 'All signature fields filled', bn: 'স্বাক্ষরের সব ক্ষেত্র পূরণ হয়েছে' },
  'signee.applyToAll': { en: 'Apply to all initials fields', bn: 'ইনিশিয়ালের সব ক্ষেত্রে ব্যবহার করুন' },
  'signee.prev': { en: 'Prev', bn: 'আগের' },
  'signee.next': { en: 'Next', bn: 'পরের' },
  'signee.finishSigning': { en: 'Finish Signing', bn: 'স্বাক্ষর সম্পন্ন করুন' },
  'signee.submitting': { en: 'Submitting...', bn: 'জমা দেওয়া হচ্ছে...' },
  'signee.helpTitle': { en: 'How to sign', bn: 'কীভাবে স্বাক্ষর করবেন' },
  'signee.help1': {
    en: '1. Create your signature by clicking "Create Signature"',
    bn: '১. "স্বাক্ষর তৈরি করুন" ক্লিক করে আপনার স্বাক্ষর তৈরি করুন',
  },
  'signee.help2': {
    en: '2. Click on each highlighted field on the document to sign',
    bn: '২. ক্ষেত্র পূরণ করতে ডকুমেন্টে হাইলাইট করা প্রতিটি জায়গায় ক্লিক করুন',
  },
  'signee.help3': {
    en: '3. Use "Next" / "Prev" buttons to navigate between fields',
    bn: '৩. এক ক্ষেত্র থেকে আরেক ক্ষেত্রে যেতে "পরের" ও "আগের" বাটন ব্যবহার করুন',
  },
  'signee.help4': {
    en: '4. Your part completes automatically after every assigned field is filled',
    bn: '৪. নির্ধারিত সব ক্ষেত্র পূরণ হলে আপনার অংশ স্বয়ংক্রিয়ভাবে সম্পন্ন হবে',
  },
  'signee.help5': {
    en: '5. The final copy becomes available after every participant has signed',
    bn: '৫. সবাই স্বাক্ষর করার পর চূড়ান্ত কপি পাওয়া যাবে',
  },
  'signee.tabUpload': { en: 'Upload', bn: 'আপলোড' },
  'signee.tabDraw': { en: 'Draw', bn: 'আঁকুন' },
  'signee.tabType': { en: 'Type', bn: 'টাইপ' },
  'signee.typedSignatureLabel': { en: 'Name for typed signature', bn: 'টাইপ করা স্বাক্ষরের নাম' },
  'signee.saveSignature': { en: 'Save Signature', bn: 'স্বাক্ষর সংরক্ষণ' },
  'signee.applyToAllSignatures': { en: 'Apply to all signature fields', bn: 'স্বাক্ষরের সব ক্ষেত্রে ব্যবহার করুন' },
  'signee.applyToAllInitials': { en: 'Apply to all initials fields', bn: 'ইনিশিয়ালের সব ক্ষেত্রে ব্যবহার করুন' },
  'signee.createYourSignature': { en: 'Create Your Signature', bn: 'আপনার স্বাক্ষর তৈরি করুন' },
  'signee.addYourInitials': { en: 'Add Your Initials', bn: 'আপনার ইনিশিয়াল যোগ করুন' },
  'signee.drawInitialsHint': { en: 'Draw your initials below. You can apply them to one field or all fields at once.', bn: 'নিচে আপনার ইনিশিয়াল আঁকুন। চাইলে একটি ক্ষেত্রে অথবা সব ক্ষেত্রে একসঙ্গে ব্যবহার করতে পারবেন।' },
  'signee.drawSignature': { en: 'Draw your signature', bn: 'আপনার স্বাক্ষর আঁকুন' },
  'signee.clearSignature': { en: 'Clear drawn signature', bn: 'আঁকা স্বাক্ষর মুছুন' },
  'signee.clear': { en: 'Clear', bn: 'মুছুন' },
  'signee.drawAbove': { en: 'Draw your signature above', bn: 'উপরে আপনার স্বাক্ষর আঁকুন' },
  'signee.typeFullName': { en: 'Type your full name', bn: 'আপনার পুরো নাম লিখুন' },
  'signee.uploadSignatureImage': { en: 'Click to upload a signature image', bn: 'স্বাক্ষরের ছবি আপলোড করতে ক্লিক করুন' },
  'signee.signatureImageFormats': { en: 'PNG, JPG, or WebP up to 2 MB', bn: 'PNG, JPG বা WebP, সর্বোচ্চ ২ MB' },
  'signee.transparentImageHint': { en: 'A transparent background gives the cleanest result.', bn: 'স্বচ্ছ পটভূমির ছবি ব্যবহার করলে স্বাক্ষর সবচেয়ে পরিষ্কার দেখাবে।' },
  'signee.signatureMethod': { en: 'Signature method', bn: 'স্বাক্ষরের পদ্ধতি' },
  'signee.uploadedSignature': { en: 'Uploaded signature preview', bn: 'আপলোড করা স্বাক্ষরের প্রিভিউ' },
  'signee.preparingSignatureImage': { en: 'Preparing signature image...', bn: 'স্বাক্ষরের ছবি প্রস্তুত হচ্ছে...' },
  'signee.signatureImagePrepareFailed': { en: 'The signature image could not be prepared. Try a smaller image.', bn: 'স্বাক্ষরের ছবি প্রস্তুত করা যায়নি। ছোট ছবি দিয়ে আবার চেষ্টা করুন।' },
  'signee.signatureImageEmpty': { en: 'The selected image is empty.', bn: 'নির্বাচিত ছবিটি খালি।' },
  'signee.signatureImageTooLarge': { en: 'The signature image must be 2 MB or smaller.', bn: 'স্বাক্ষরের ছবি ২ MB বা তার কম হতে হবে।' },
  'signee.signatureImageTypeInvalid': { en: 'Use a PNG, JPG, or WebP image.', bn: 'PNG, JPG অথবা WebP ছবি ব্যবহার করুন।' },
  'signee.typeHere': { en: 'Type here...', bn: 'এখানে লিখুন...' },
  'signee.fieldSaveFailed': {
    en: 'This field could not be saved. Your document was refreshed, so you can try again.',
    bn: 'এই ক্ষেত্রটি সংরক্ষণ করা যায়নি। ডকুমেন্টটি রিফ্রেশ করা হয়েছে, এখন আবার চেষ্টা করুন।',
  },
  'signee.completionConfirmFailed': {
    en: 'Your fields were saved, but completion could not be confirmed. Check your connection and try again.',
    bn: 'আপনার ক্ষেত্রগুলো সংরক্ষিত হয়েছে, কিন্তু কাজ সম্পন্ন হওয়ার বিষয়টি নিশ্চিত করা যায়নি। সংযোগ পরীক্ষা করে আবার চেষ্টা করুন।',
  },
  'signee.completionCheckFailed': {
    en: 'Your fields were saved, but document completion could not be verified. Check your connection and try again.',
    bn: 'আপনার ক্ষেত্রগুলো সংরক্ষিত হয়েছে, কিন্তু ডকুমেন্ট সম্পন্ন হওয়া যাচাই করা যায়নি। সংযোগ পরীক্ষা করে আবার চেষ্টা করুন।',
  },
  'signee.retryingCompletion': { en: 'Checking...', bn: 'যাচাই হচ্ছে...' },
  'signee.finalizeFailed': {
    en: 'Everyone has signed, but the document could not be finalized. Please try again.',
    bn: 'সকলেই স্বাক্ষর করেছেন, কিন্তু ডকুমেন্টটি চূড়ান্ত করা যায়নি। আবার চেষ্টা করুন।',
  },
  'signee.signedDocumentGenerateFailed': {
    en: 'The signed document could not be generated. Please try again.',
    bn: 'স্বাক্ষরিত ডকুমেন্ট তৈরি করা যায়নি। আবার চেষ্টা করুন।',
  },
  'signee.signedPdfGenerateFailed': {
    en: 'The signed PDF could not be generated. Please try again.',
    bn: 'স্বাক্ষরিত PDF তৈরি করা যায়নি। আবার চেষ্টা করুন।',
  },
  'signee.openAuditTrail': { en: 'Open audit trail', bn: 'অডিট ইতিহাস খুলুন' },
  'signee.previousUnsignedField': { en: 'Previous unsigned field', bn: 'আগের অসম্পূর্ণ ক্ষেত্র' },
  'signee.nextUnsignedField': { en: 'Next unsigned field', bn: 'পরের অসম্পূর্ণ ক্ষেত্র' },
  'signee.collapsePanel': { en: 'Collapse signing panel', bn: 'স্বাক্ষর প্যানেল বন্ধ করুন' },
  'signee.expandPanel': { en: 'Expand signing panel', bn: 'স্বাক্ষর প্যানেল খুলুন' },
  'signee.signingProgress': { en: 'Signing progress', bn: 'স্বাক্ষরের অগ্রগতি' },
  'signee.signingDate': { en: 'Signing date', bn: 'স্বাক্ষরের তারিখ' },
  'signee.fieldText': { en: 'Field text', bn: 'ক্ষেত্রের লেখা' },
  'signee.signedValue': { en: 'Signed field value', bn: 'স্বাক্ষরিত ক্ষেত্রের মান' },
  'signee.signaturePreview': { en: 'Signature preview', bn: 'স্বাক্ষরের প্রিভিউ' },
  'signee.applyToThis': { en: 'Apply here', bn: 'শুধু এখানে ব্যবহার করুন' },
  'signee.applyToEveryField': { en: 'Apply to all', bn: 'সব ক্ষেত্রে ব্যবহার করুন' },
  'signee.activateField': { en: 'Select to complete this field.', bn: 'ক্ষেত্রটি পূরণ করতে নির্বাচন করুন।' },
  'signee.tapToAddDate': { en: 'Tap to add date', bn: 'তারিখ যোগ করতে ট্যাপ করুন' },
  'signee.tapToEnterText': { en: 'Tap to enter text', bn: 'লেখা যোগ করতে ট্যাপ করুন' },
  'signee.tapToSign': { en: 'Tap to sign', bn: 'স্বাক্ষর করতে ট্যাপ করুন' },
  'signee.tapAnyField': { en: 'Tap any field on the PDF to fill it', bn: 'PDF-এর যেকোনো নির্ধারিত ক্ষেত্র পূরণ করতে সেখানে ট্যাপ করুন' },
  'signee.allYourFieldsSigned': { en: 'All your fields are complete!', bn: 'আপনার সব ক্ষেত্র পূরণ হয়েছে!' },
  'signee.saveInitials': { en: 'Save Initials', bn: 'ইনিশিয়াল সংরক্ষণ করুন' },
  'signee.applyToAllCount': { en: 'Apply to all ({count})', bn: 'সব ক্ষেত্রে ব্যবহার করুন ({count})' },

  // ─── Shared document viewer ───
  'viewer.page': { en: 'page', bn: 'পৃষ্ঠা' },
  'viewer.pages': { en: 'pages', bn: 'পৃষ্ঠা' },
  'viewer.zoomOut': { en: 'Zoom out', bn: 'ছোট করুন' },
  'viewer.zoomIn': { en: 'Zoom in', bn: 'বড় করুন' },
  'viewer.resetZoom': { en: 'Reset zoom', bn: 'জুম আগের অবস্থায় নিন' },
  'viewer.pdfLoadFailed': { en: 'The PDF could not be loaded. Check your connection and try again.', bn: 'PDF লোড করা যায়নি। সংযোগ পরীক্ষা করে আবার চেষ্টা করুন।' },
  'viewer.loadingPdf': { en: 'Loading PDF...', bn: 'PDF লোড হচ্ছে...' },
  'viewer.tryAgain': { en: 'Try again', bn: 'আবার চেষ্টা করুন' },
  'viewer.retrying': { en: 'Refreshing...', bn: 'রিফ্রেশ হচ্ছে...' },
  'viewer.pdfPage': { en: 'PDF page', bn: 'PDF পৃষ্ঠা' },
  'viewer.placeCenterHint': { en: 'Press Enter to place the selected field in the center.', bn: 'নির্বাচিত ক্ষেত্রটি মাঝখানে রাখতে Enter চাপুন।' },
  'viewer.signingProgress': { en: 'Document signing progress', bn: 'ডকুমেন্ট স্বাক্ষরের অগ্রগতি' },
  'viewer.viewOnly': { en: 'View only', bn: 'শুধু দেখুন' },
  'viewer.signedCount': { en: '{signed} / {total} signed', bn: '{signed} / {total} স্বাক্ষরিত' },
  'viewer.hideDetails': { en: 'Hide details', bn: 'বিস্তারিত লুকান' },
  'viewer.showDetails': { en: 'Show document details', bn: 'ডকুমেন্টের বিস্তারিত দেখান' },
  'viewer.finalCopyPending': { en: 'Final signed copy is being prepared', bn: 'চূড়ান্ত স্বাক্ষরিত কপি প্রস্তুত হচ্ছে' },
  'viewer.finalCopyPendingDesc': {
    en: 'Everyone has signed, but the final PDF is not ready yet. Please try this link again shortly.',
    bn: 'সবাই স্বাক্ষর করেছেন, তবে চূড়ান্ত PDF এখনো প্রস্তুত নয়। কিছুক্ষণ পর এই লিঙ্কটি আবার খুলুন।',
  },
  'viewer.checkFinalCopy': { en: 'Check for signed copy', bn: 'স্বাক্ষরিত কপি পরীক্ষা করুন' },
  'viewer.finalCopyRefreshFailed': {
    en: 'The signed copy could not be checked. Check your connection and try again.',
    bn: 'স্বাক্ষরিত কপি পরীক্ষা করা যায়নি। সংযোগ পরীক্ষা করে আবার চেষ্টা করুন।',
  },
  'viewer.originalCopyTitle': { en: 'Original document shown', bn: 'মূল ডকুমেন্ট দেখানো হচ্ছে' },
  'viewer.originalCopyDesc': {
    en: 'This page shows the original uploaded PDF. The completed signed copy is sent to recipients by email when it is ready.',
    bn: 'এই পৃষ্ঠায় আপলোড করা মূল PDF দেখানো হচ্ছে। সম্পন্ন স্বাক্ষরিত কপি প্রস্তুত হলে প্রাপকদের ইমেইলে পাঠানো হয়।',
  },

  // ─── Audit trail ───
  'audit.title': { en: 'Audit trail', bn: 'অডিট ইতিহাস' },
  'audit.trail': { en: 'Event', bn: 'ঘটনা' },
  'audit.user': { en: 'User', bn: 'ব্যবহারকারী' },
  'audit.timeLocation': { en: 'Time and location', bn: 'সময় ও অবস্থান' },
  'audit.timeNetwork': { en: 'Time and network', bn: 'সময় ও নেটওয়ার্ক' },
  'audit.recordedActivity': { en: 'Recorded document activity', bn: 'ডকুমেন্টের সংরক্ষিত কার্যক্রম' },
  'audit.recordedActivityDesc': {
    en: 'Events are shown in chronological order using the timestamps captured by Somadhan Sign.',
    bn: 'Somadhan Sign-এ সংরক্ষিত সময় অনুযায়ী ঘটনাগুলো ধারাবাহিকভাবে দেখানো হয়েছে।',
  },
  'audit.event': { en: 'event', bn: 'ঘটনা' },
  'audit.events': { en: 'events', bn: 'ঘটনা' },
  'audit.participant': { en: 'participant', bn: 'অংশগ্রহণকারী' },
  'audit.participants': { en: 'participants', bn: 'অংশগ্রহণকারী' },
  'audit.timesInUtc': { en: 'Times in UTC', bn: 'সময় UTC-তে' },
  'audit.networkAddress': { en: 'Network:', bn: 'নেটওয়ার্ক:' },
  'audit.loading': { en: 'Loading audit history', bn: 'অডিট ইতিহাস লোড হচ্ছে' },
  'audit.noActivity': { en: 'No activity recorded yet', bn: 'এখনো কোনো কার্যক্রম রেকর্ড হয়নি' },
  'audit.loadFailed': {
    en: 'The audit trail could not be loaded. Check your connection and try again.',
    bn: 'অডিট ইতিহাস লোড করা যায়নি। সংযোগ পরীক্ষা করে আবার চেষ্টা করুন।',
  },
  'audit.documentCreated': { en: 'Document created', bn: 'ডকুমেন্ট তৈরি হয়েছে' },
  'audit.documentSent': { en: 'Document sent', bn: 'ডকুমেন্ট পাঠানো হয়েছে' },
  'audit.documentViewed': { en: 'Document viewed', bn: 'ডকুমেন্ট দেখা হয়েছে' },
  'audit.documentSigned': { en: 'Document signed', bn: 'ডকুমেন্ট স্বাক্ষরিত হয়েছে' },
  'audit.fieldSigned': { en: 'Field completed', bn: 'ক্ষেত্র পূরণ হয়েছে' },
  'audit.allFieldsSigned': { en: 'All fields completed', bn: 'সব ক্ষেত্র সম্পন্ন হয়েছে' },
  'audit.signatureApplied': { en: 'Signature applied', bn: 'স্বাক্ষর যোগ হয়েছে' },
  'audit.initialsAdded': { en: 'Initials added', bn: 'ইনিশিয়াল যোগ হয়েছে' },
  'audit.dateFilled': { en: 'Date filled', bn: 'তারিখ পূরণ হয়েছে' },
  'audit.checkboxChecked': { en: 'Checkbox selected', bn: 'চেকবক্সে টিক দেওয়া হয়েছে' },
  'audit.textEntered': { en: 'Text entered', bn: 'টেক্সট যোগ হয়েছে' },
  'audit.documentCompleted': { en: 'Document completed', bn: 'ডকুমেন্ট সম্পন্ন হয়েছে' },
  'audit.sentForSigning': { en: 'Sent for signing', bn: 'স্বাক্ষরের জন্য পাঠানো হয়েছে' },
  'audit.reminderSent': { en: 'Reminder sent', bn: 'রিমাইন্ডার পাঠানো হয়েছে' },
  'audit.consentGiven': { en: 'Electronic signature consent given', bn: 'ইলেকট্রনিক স্বাক্ষরের সম্মতি দেওয়া হয়েছে' },
  'audit.completionEmailsSent': { en: 'Completion emails sent', bn: 'কাজ সম্পন্ন হওয়ার ইমেইল পাঠানো হয়েছে' },
  'audit.documentCancelled': { en: 'Document cancelled', bn: 'ডকুমেন্ট বাতিল করা হয়েছে' },
}

export const useLanguageStore = create<LanguageState>((set, get) => {
  const saved = readLocalPreference('somadhan-lang') as Language | null
  const initialLanguage = saved === 'bn' ? 'bn' : 'en'
  if (typeof document !== 'undefined') document.documentElement.lang = initialLanguage

  return {
    lang: initialLanguage,
    setLang: (lang) => {
      writeLocalPreference('somadhan-lang', lang)
      document.documentElement.lang = lang
      set({ lang })
    },
    toggle: () => {
      const next = get().lang === 'en' ? 'bn' : 'en'
      writeLocalPreference('somadhan-lang', next)
      document.documentElement.lang = next
      set({ lang: next })
    },
    t: (key: string) => {
      const entry = translations[key]
      if (!entry) return key
      return entry[get().lang] || entry.en || key
    },
  }
})
